export { DISTILLY_ERROR_CODES, DistillyError } from "./errors.js";
export type { DistillyErrorCode, DistillyWireError } from "./errors.js";

export { BUILTIN_HOSTS, BUILTIN_PEOPLE_SPACE_ID } from "./ids.js";
export type {
  Branded,
  BriefContractDigest,
  BriefMaterialRef,
  CaptureAuditRef,
  CaptureScopeDigest,
  ClaimId,
  ContentDigest,
  ConversationSourceKey,
  EventId,
  FacetPath,
  FactChecksum,
  HostName,
  IsoDateTime,
  JobId,
  LeaseId,
  LeaseOwnerId,
  MaterialId,
  MaterialSetHash,
  ProvenanceDigest,
  RawId,
  RelationId,
  RequestId,
  SourceGroupKey,
  SpaceId,
  SubjectId,
  VersionId,
} from "./ids.js";

export { FACT_LIMITS, JSON_SCHEMA_DIALECT, WIRE_LIMITS } from "./json.js";
export type { JsonObject, JsonPrimitive, JsonValue } from "./json.js";

export { WIRE_VERSION } from "./wire.js";
export type { RuntimeSchema, WireFailure, WireRequest, WireSuccess } from "./wire.js";

export type {
  ActorContext,
  BriefCapacity,
  ClientSessionContext,
  MutationContext,
} from "./values.js";
export type {
  DistillCommitTransactionBase,
  DistillCommitTransactionRecord,
  DistillLeaseTransactionMethod,
  DistillLeaseTransactionRecord,
  EventRecord,
  FactEnvelope,
  OperationFact,
  OperationRecord,
  OperationScope,
  OperationTombstoneRecord,
  PendingLeaseMarker,
  PendingJobMarker,
  ReviewDecisionTransactionMethod,
  ReviewDecisionTransactionRecord,
  RollbackTransactionBase,
  RollbackTransactionRecord,
  SpaceRecord,
  StoredOperationResult,
  SubjectRecord,
  SubjectStateRecord,
  TransactionRecord,
  VersionClaimsSnapshot,
  VersionMaterialEntry,
} from "./values/facts.js";
export type {
  AmbiguousSubjectCandidates,
  CreateSubjectInput,
  IdentityHint,
  PurgeResult,
  PurgeSubjectInput,
  ResolveSubjectInput,
  ResolveSubjectResult,
  SpaceSummary,
  SubjectLifecycle,
  SubjectPage,
  SubjectQuery,
  SubjectRef,
  SubjectSelector,
  SubjectStatus,
  SubjectSummary,
} from "./values/subjects.js";
export type {
  ArtifactLocator,
  CorrectionProvenance,
  FileIngestItemResult,
  GetMaterialInput,
  HostExtractionMethod,
  IngestFilesInput,
  IngestFilesResult,
  IngestInput,
  IngestItemResult,
  IngestResult,
  IngestSubjectTarget,
  MaterialInput,
  MaterialPage,
  MaterialQuery,
  MaterialRecord,
  MaterialSource,
  MaterialSourceInput,
  MaterialSummary,
  MaterialView,
  ParserExtractionMethod,
  SourceAccess,
  SourceDiversityStatus,
  SourceGroup,
  SourceGroupBasis,
  SourceGroupCaution,
  SourceGroupingContext,
  SourceGroupingSnapshot,
  SourceMedium,
  SourceRole,
  TextDerivation,
  TextDerivationInput,
} from "./values/materials.js";
export type {
  BaselineEvidenceDraft,
  BriefEvidenceDraft,
  Claim,
  ClaimDraft,
  ClaimOperation,
  ClaimStatus,
  CoreFacetName,
  DistillPatch,
  EvidenceDraft,
  EvidenceRef,
  EvidenceStrength,
} from "./values/claims.js";
export type { RelationOperationDraft } from "./values/relations.js";
export type {
  CorrectInput,
  CorrectionDraft,
  GetProfileInput,
  LibraryEntry,
  LibraryPage,
  LibraryPrivacy,
  LibraryQuery,
  Maturity,
  Profile,
  ProfileDiff,
  QualitySummary,
  RebuildResult,
} from "./values/profiles.js";
export type {
  BriefContract,
  BriefEvidenceFact,
  BriefInput,
  BriefMaterial,
  HostDistillBriefing,
  HostDistillContract,
  JobLease,
  PendingFilter,
  PendingJob,
  PendingJobFailure,
  PublicJobState,
  RedistillInput,
  ReleaseLeaseInput,
  RenewLeaseInput,
} from "./values/jobs.js";
export type {
  CommitInput,
  CommitResult,
  CreatedDisposition,
  DiffInput,
  LineageEvent,
  LineageInput,
  LineagePage,
  ReviewActionInput,
  ReviewItem,
  ReviewLaunch,
  ReviewPage,
  ReviewQuery,
  ReviewReason,
  ReviewRef,
  RollbackInput,
  VersionPage,
  VersionQuery,
  VersionCreation,
  VersionMaterialManifest,
  VersionRecord,
  VersionStatus,
  VersionSummary,
} from "./values/versions.js";
export type {
  BundleExportInput,
  BundleExportResult,
  BundleImportInput,
  BundleImportResult,
  BundleInspectInput,
  BundleInspection,
  CapabilityAvailability,
  CapturedPrivateTranscript,
  DoctorInput,
  DoctorSnapshot,
  ExportOptions,
  ExportRef,
  ExtensionStatus,
  HostCapabilities,
  HostEnvironment,
  HostExportInput,
  HostPreflight,
  HostPreflightEvidence,
  InstallInput,
  InstallOptions,
  InstallRef,
  PrivateUiCaptureActionAbortReason,
  PrivateUiCaptureActionResult,
  PrivateUiCaptureAuditStop,
  PrivateUiCaptureAuthorization,
  PrivateUiCaptureGrantStatus,
  PrivateUiCaptureGuardStopReason,
  PrivateUiCaptureIngestResult,
  PrivateUiCaptureRange,
  PrivateUiCaptureRefusalReason,
  PrivateUiCaptureRefused,
  PrivateUiCaptureScope,
  PrivateUiCaptureStopReason,
  SystemBackupInput,
  SystemBackupResult,
  SystemRestoreInput,
  SystemRestoreResult,
  UninstallInput,
} from "./values/hosts.js";

export type {
  EmptyResult,
  EngineMethodMap,
  Method,
  MethodSchemas,
  MutationMethodName,
  QueryMethodName,
} from "./methods.js";
export type {
  CoreEngineClient,
  CoreMethodName,
  EngineAdministrationClient,
  EngineClient,
  RuntimeOwnedMethodName,
  Unsubscribe,
} from "./engine-client.js";
export type { EngineEvent, EngineEventDecodeHandlers, EngineEventDecodeResult } from "./events.js";

export { distillyMcpTools } from "./mcp.js";
export type {
  CommitToolInput,
  CommitToolOutput,
  CommitToolValue,
  CorrectToolInput,
  CorrectToolOutput,
  CorrectToolValue,
  DistillyMcpToolName,
  GetToolInput,
  GetToolOutput,
  GetToolValue,
  IngestToolInput,
  IngestToolOutput,
  IngestToolValue,
  JsonSchemaObject,
  McpToolAnnotations,
  McpToolContract,
  PendingToolInput,
  PendingToolOutput,
  PendingToolValue,
} from "./mcp.js";

export {
  briefContractDigestSchema,
  briefMaterialRefSchema,
  captureAuditRefSchema,
  captureScopeDigestSchema,
  claimIdSchema,
  contentDigestSchema,
  conversationSourceKeySchema,
  eventIdSchema,
  facetPathSchema,
  factChecksumSchema,
  hostNameSchema,
  isoDateTimeSchema,
  jobIdSchema,
  leaseIdSchema,
  leaseOwnerIdSchema,
  materialIdSchema,
  materialSetHashSchema,
  provenanceDigestSchema,
  rawIdSchema,
  relationIdSchema,
  requestIdSchema,
  sourceGroupKeySchema,
  spaceIdSchema,
  subjectIdSchema,
  versionIdSchema,
} from "./schemas/ids.js";
export {
  actorContextSchema,
  briefCapacitySchema,
  clientSessionContextSchema,
  mutationContextSchema,
} from "./schemas/context.js";
export {
  distillCommitTransactionRecordSchema,
  distillLeaseTransactionMethodSchema,
  distillLeaseTransactionRecordSchema,
  eventRecordSchema,
  factEnvelopeSchema,
  operationFactSchema,
  operationRecordSchema,
  operationScopeSchema,
  operationTombstoneRecordSchema,
  pendingLeaseMarkerSchema,
  pendingJobMarkerSchema,
  reviewDecisionTransactionMethodSchema,
  reviewDecisionTransactionRecordSchema,
  rollbackTransactionRecordSchema,
  spaceRecordSchema,
  subjectRecordSchema,
  subjectStateRecordSchema,
  transactionRecordSchema,
  versionClaimsSnapshotSchema,
  versionMaterialEntrySchema,
  versionMaterialManifestSchema,
  versionRecordSchema,
} from "./schemas/facts.js";
export {
  ambiguousSubjectCandidatesSchema,
  createSubjectInputSchema,
  identityHintSchema,
  maturitySchema,
  purgeResultSchema,
  purgeSubjectInputSchema,
  resolveSubjectInputSchema,
  resolveSubjectResultSchema,
  spaceSummarySchema,
  subjectLifecycleSchema,
  subjectPageSchema,
  subjectQuerySchema,
  subjectRefSchema,
  subjectSelectorSchema,
  subjectStatusSchema,
  subjectSummarySchema,
} from "./schemas/subjects.js";
export {
  artifactLocatorSchema,
  correctionProvenanceSchema,
  fileIngestItemResultSchema,
  getMaterialInputSchema,
  hostExtractionMethodSchema,
  ingestFilesInputSchema,
  ingestFilesResultSchema,
  ingestInputSchema,
  ingestItemResultSchema,
  ingestResultSchema,
  ingestSubjectTargetSchema,
  materialInputSchema,
  materialPageSchema,
  materialQuerySchema,
  materialRecordSchema,
  materialSourceInputSchema,
  materialSourceSchema,
  materialSummarySchema,
  materialViewSchema,
  parserExtractionMethodSchema,
  sourceAccessSchema,
  sourceDiversityStatusSchema,
  sourceGroupBasisSchema,
  sourceGroupCautionSchema,
  sourceGroupSchema,
  sourceGroupingContextSchema,
  sourceMediumSchema,
  sourceRoleSchema,
  textDerivationInputSchema,
  textDerivationSchema,
} from "./schemas/materials.js";
export {
  claimDraftSchema,
  claimOperationSchema,
  claimSchema,
  claimStatusSchema,
  coreFacetNameSchema,
  distillPatchSchema,
  evidenceDraftSchema,
  evidenceRefSchema,
  evidenceStrengthSchema,
  relationOperationDraftSchema,
} from "./schemas/claims.js";
export {
  correctInputSchema,
  correctionDraftSchema,
  getProfileInputSchema,
  libraryEntrySchema,
  libraryPageSchema,
  libraryPrivacySchema,
  libraryQuerySchema,
  profileDiffSchema,
  profileDiffWithBaselineSchema,
  profileSchema,
  qualitySummarySchema,
  rebuildResultSchema,
} from "./schemas/profiles.js";
export {
  briefContractSchema,
  briefEvidenceFactSchema,
  briefInputSchema,
  briefMaterialSchema,
  hostDistillBriefingSchema,
  hostDistillContractSchema,
  jobLeaseSchema,
  pendingFilterSchema,
  pendingJobFailureSchema,
  pendingJobSchema,
  publicJobStateSchema,
  redistillInputSchema,
  releaseLeaseInputSchema,
  renewLeaseInputSchema,
} from "./schemas/jobs.js";
export {
  commitInputSchema,
  commitResultSchema,
  createdDispositionSchema,
  diffInputSchema,
  lineageEventSchema,
  lineageInputSchema,
  lineagePageSchema,
  reviewActionInputSchema,
  reviewItemSchema,
  reviewLaunchSchema,
  reviewPageSchema,
  reviewQuerySchema,
  reviewReasonSchema,
  reviewRefSchema,
  rollbackInputSchema,
  versionCreationSchema,
  versionPageSchema,
  versionQuerySchema,
  versionStatusSchema,
  versionSummarySchema,
} from "./schemas/versions.js";
export {
  bundleExportInputSchema,
  bundleExportResultSchema,
  bundleImportInputSchema,
  bundleImportResultSchema,
  bundleInspectInputSchema,
  bundleInspectionSchema,
  capabilityAvailabilitySchema,
  capturedPrivateTranscriptSchema,
  doctorInputSchema,
  doctorSnapshotSchema,
  exportOptionsSchema,
  exportRefSchema,
  extensionStatusSchema,
  hostCapabilitiesSchema,
  hostExportInputSchema,
  hostPreflightEvidenceSchema,
  hostPreflightSchema,
  installInputSchema,
  installOptionsSchema,
  installRefSchema,
  privateUiCaptureActionAbortReasonSchema,
  privateUiCaptureActionResultSchema,
  privateUiCaptureAuditStopSchema,
  privateUiCaptureAuthorizationSchema,
  privateUiCaptureGrantStatusSchema,
  privateUiCaptureGuardStopReasonSchema,
  privateUiCaptureIngestResultSchema,
  privateUiCaptureRangeSchema,
  privateUiCaptureRefusalReasonSchema,
  privateUiCaptureRefusedSchema,
  privateUiCaptureScopeSchema,
  privateUiCaptureStopReasonSchema,
  systemBackupInputSchema,
  systemBackupResultSchema,
  systemRestoreInputSchema,
  systemRestoreResultSchema,
  uninstallInputSchema,
} from "./schemas/hosts.js";
export { decodeEngineEvent, engineEventSchema } from "./schemas/events.js";
export { engineAdministrationSchemas, engineMethodSchemas } from "./schemas/methods.js";
export {
  distillyErrorCodeSchema,
  distillyWireErrorSchema,
  wireFailureSchema,
  wireRequestSchema,
  wireSuccessSchema,
} from "./schemas/wire.js";
