export { ProseHero } from './components/prose-hero'
export { ProseLink } from './components/prose-link'
export { ProseShell } from './components/prose-shell'
export { PROSE_SPACING, PROSE_TYPE } from './constants'
export { ProsePage } from './prose-page'
export type { LegalBlock, LegalPageConfig, LegalSection } from './types'
