// Bypassing the '@' alias to force TypeScript to find the file
import { EmptyState } from "../../../components/surface-state";
import { getEnv } from "../../../lib/kv";
import { buildPageMetadata } from "../../../lib/page-meta";

// Define the exact structure of the Digest data to fix all the 'any' type errors
interface DigestSection {
  heading: string;
  items: string[];
}

interface WeeklyDigest {
  weekId: string;
  titleEn: string;
  titleZh: string;
  summaryEn: string;
  summaryZh: string;
  sections: DigestSection[];
  generatedAt: string;
}

export const revalidate = 3600; // Cache page updates hourly

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  return buildPageMetadata({
    path: "/digest",
    locale,
    title: isZh ? "社区摘要 · Codewhale" : "Community Digest · Codewhale",
    description: isZh
      ? "Codewhale 每周社区更新存档：由维护者审核的摘要。"
      : "Archive of weekly Codewhale community updates — maintainer-approved summaries.",
  });
}

export default async function DigestArchivePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";

  // 1. Get the correct project environment bindings
  const env = await getEnv();
  const kv = env.CURATED_KV;

  // Fallback array if no data is found or if KV isn't active in dev
  let digests: WeeklyDigest[] = [];

  if (kv) {
    try {
      // Fetch all weekly digest keys generated by the agent tasks
      const { keys } = await kv.list({ prefix: "digest:weekly-" });

      if (keys && keys.length > 0) {
        const digestsRaw = await Promise.all(
          keys.map(async (k: { name: string }) => {
            const data = await kv.get(k.name);
            return data;
          })
        );

        // Parse each entry independently so a single malformed record can't
        // blank the entire archive — skip only the bad ones.
        digests = digestsRaw
          .filter((item: string | null): item is string => Boolean(item))
          .flatMap((item: string) => {
            try {
              return [JSON.parse(item) as WeeklyDigest];
            } catch (e) {
              console.error("Skipping malformed digest entry:", e);
              return [];
            }
          })
          .sort((a: WeeklyDigest, b: WeeklyDigest) =>
            new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
          );
      }
    } catch (e) {
      console.error("Error reading from KV:", e);
    }
  }

  // Handle empty state gracefully
  if (digests.length === 0) {
    return (
      <div className="route-state">
        <h1 className="font-display text-3xl mb-6 tracking-crisp text-ink">
          {isZh ? "社区摘要" : "Community Digest"}
        </h1>
        <EmptyState
          locale={locale}
          body={
            isZh
              ? "还没有经维护者审核的每周摘要。摘要在 cron 生成并审核后才会出现在这里。"
              : "No maintainer-approved weekly digest exists yet. One appears here only after the cron draft has been reviewed."
          }
        />
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <h1 className="font-display text-4xl mb-2 tracking-crisp text-ink">
        {isZh ? "每周社区更新" : "Weekly Community Updates"}
      </h1>
      <p className="text-ink-mute mb-8">
        {isZh ? "由 Codewhale 维护者审核的摘要" : "Maintainer-approved summaries from Codewhale"}
      </p>

      <div className="space-y-12">
        {digests.map((digest: WeeklyDigest) => (
          <article key={digest.weekId} className="border hairline rounded-lg p-6 bg-paper-card">
            <header className="mb-6 hairline-b pb-4">
              <span className="pill">
                {digest.weekId}
              </span>
              <h2 className="font-display text-2xl mt-3 text-ink">{digest.titleEn}</h2>
              <h3 className="font-cjk text-lg text-ink-soft mt-1">{digest.titleZh}</h3>
            </header>

            <div className="mb-6 space-y-4">
              <p className="text-ink-soft leading-relaxed">{digest.summaryEn}</p>
              <p className="text-ink-mute leading-relaxed italic">{digest.summaryZh}</p>
            </div>

            <div className="space-y-6">
              {digest.sections.map((section: DigestSection, idx: number) => (
                <section key={idx} className="border-l-2 border-paper-edge pl-4">
                  <h4 className="font-display text-lg mb-2 text-ink">{section.heading}</h4>
                  <ul className="list-disc list-inside space-y-1 text-ink-soft font-mono text-sm">
                    {section.items.map((item: string, itemIdx: number) => (
                      <li key={itemIdx}>{item}</li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}
