/**
 * The Create PR `web_search` implementation, shared by its creation and optional
 * Babysit continuation sandbox phases and written at runtime (mirroring
 * `cloud-review-tools-script.ts`).
 *
 * These phases run the Pi CLI inside E2B/Daytona with no host in the loop and no stdin channel, so
 * they cannot call `executeTool` and must issue their own bounded `fetch`. That makes the request
 * construction and normalization exist twice — here and in `tool.ts` plus `normalize.ts`. Every
 * value the two copies must agree on is interpolated from those modules rather than retyped, so the
 * duplication is confined to control flow, which the offline loader test covers per provider.
 *
 * A load failure fails the run loudly rather than silently disabling search: Pi treats an extension
 * load error as fatal and exits non-zero, which the sandbox backends surface as a failed run.
 */

import {
  EXA_MAX_TEXT_CHARACTERS,
  PI_SEARCH_BUDGET_MESSAGE,
  PI_SEARCH_DEFAULT_RESULTS,
  PI_SEARCH_MAX_CALLS_PER_EXECUTION,
  PI_SEARCH_MAX_DATE_LENGTH,
  PI_SEARCH_MAX_ENVELOPE_BYTES,
  PI_SEARCH_MAX_QUERY_LENGTH,
  PI_SEARCH_MAX_RESULTS,
  PI_SEARCH_MAX_SNIPPET_LENGTH,
  PI_SEARCH_MAX_TITLE_LENGTH,
  PI_SEARCH_MAX_URL_LENGTH,
  PI_SEARCH_MIN_RESULTS,
  PI_SEARCH_NO_RESULTS_MESSAGE,
  PI_SEARCH_PROMPT_GUIDELINES,
  PI_SEARCH_TIMEOUT_MS,
  PI_SEARCH_TOOL_DESCRIPTION,
  PI_SEARCH_TOOL_NAME,
  PI_SEARCH_TOOL_PARAMETERS,
  PI_SEARCH_TRUNCATED_MESSAGE,
} from '@/executor/handlers/pi/search/normalize'

/**
 * Written outside `REPO_DIR` so `git add -A` cannot stage it into the user's pull request. The agent
 * can still read or overwrite it — it holds bash on the sandbox — but Pi loads extensions once at
 * startup, so a later rewrite changes nothing about the run.
 */
export const PI_SEARCH_EXTENSION_PATH = '/workspace/sim-search-extension.ts'

export const PI_SEARCH_PROVIDER_ENV_VAR = 'SIM_SEARCH_PROVIDER'
/**
 * Delivered as an environment variable, like the model key next to it, which means the agent can
 * read it: Pi copies its own environment into every bash child. That is inherent to Create PR
 * running the model inside the sandbox, and it is why search refuses a Sim-hosted key in any mode —
 * only a key the user supplied themselves can ever get here.
 */
export const PI_SEARCH_API_KEY_ENV_VAR = 'SIM_SEARCH_API_KEY'

/** Raw-response ceiling for the sandbox path; the host path relies on `executeTool`'s own limit. */
const MAX_RESPONSE_BYTES = 1024 * 1024

export const PI_SEARCH_EXTENSION_SOURCE = `/**
 * Generated by Sim. Provides the Pi Coding Agent's ${PI_SEARCH_TOOL_NAME} tool inside the Create PR
 * sandbox. Mirrors apps/sim/executor/handlers/pi/search/{normalize,tool}.ts.
 */

const TOOL_NAME = ${JSON.stringify(PI_SEARCH_TOOL_NAME)}
const TIMEOUT_MS = ${PI_SEARCH_TIMEOUT_MS}
const MAX_RESPONSE_BYTES = ${MAX_RESPONSE_BYTES}
const MAX_QUERY_LENGTH = ${PI_SEARCH_MAX_QUERY_LENGTH}
const MIN_RESULTS = ${PI_SEARCH_MIN_RESULTS}
const MAX_RESULTS = ${PI_SEARCH_MAX_RESULTS}
const DEFAULT_RESULTS = ${PI_SEARCH_DEFAULT_RESULTS}
const MAX_TITLE_LENGTH = ${PI_SEARCH_MAX_TITLE_LENGTH}
const MAX_SNIPPET_LENGTH = ${PI_SEARCH_MAX_SNIPPET_LENGTH}
const MAX_DATE_LENGTH = ${PI_SEARCH_MAX_DATE_LENGTH}
const MAX_URL_LENGTH = ${PI_SEARCH_MAX_URL_LENGTH}
const MAX_ENVELOPE_BYTES = ${PI_SEARCH_MAX_ENVELOPE_BYTES}
const NO_RESULTS_MESSAGE = ${JSON.stringify(PI_SEARCH_NO_RESULTS_MESSAGE)}
const TRUNCATED_MESSAGE = ${JSON.stringify(PI_SEARCH_TRUNCATED_MESSAGE)}
const EXA_MAX_TEXT_CHARACTERS = ${EXA_MAX_TEXT_CHARACTERS}
const MAX_CALLS_PER_RUN = ${PI_SEARCH_MAX_CALLS_PER_EXECUTION}
const BUDGET_MESSAGE = ${JSON.stringify(PI_SEARCH_BUDGET_MESSAGE)}

const PROVIDER_LABELS = {
  exa: "Exa",
  serper: "Serper",
  parallel: "Parallel AI",
  firecrawl: "Firecrawl",
}

function buildRequest(provider, apiKey, query, numResults) {
  if (provider === "exa") {
    return {
      url: "https://api.exa.ai/search",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey },
      body: {
        query: query,
        numResults: numResults,
        contents: { text: { maxCharacters: EXA_MAX_TEXT_CHARACTERS } },
      },
    }
  }
  if (provider === "serper") {
    return {
      url: "https://google.serper.dev/search",
      headers: { "X-API-KEY": apiKey, "Content-Type": "application/json" },
      body: { q: query, num: numResults },
    }
  }
  if (provider === "parallel") {
    return {
      url: "https://api.parallel.ai/v1beta/search",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "parallel-beta": "search-extract-2025-10-10",
      },
      body: { objective: query, max_results: numResults },
    }
  }
  if (provider === "firecrawl") {
    return {
      url: "https://api.firecrawl.dev/v2/search",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + apiKey },
      // Firecrawl forwards \`timeout\` into its own request as a server-side budget; sending it
      // keeps the sandbox path's effective deadline the same as the host path's.
      body: { query: query, limit: numResults, timeout: TIMEOUT_MS },
    }
  }
  throw new Error("Unsupported search provider")
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function asText(value) {
  return typeof value === "string" ? value : ""
}

function firstText(...candidates) {
  for (const candidate of candidates) {
    if (typeof candidate === "string" && candidate.trim()) return candidate
    if (Array.isArray(candidate)) {
      const found = candidate.find((item) => typeof item === "string" && item.trim())
      if (typeof found === "string") return found
    }
  }
  return ""
}

function collapseWhitespace(value) {
  return value.replace(/\\s+/g, " ").trim()
}

const URL_FORBIDDEN_CHARACTERS = /[\\s\\u0000-\\u001f\\u007f]/

function usableUrl(value) {
  const raw = asText(value).trim()
  if (!raw || raw.length > MAX_URL_LENGTH) return undefined
  if (!/^https?:\\/\\//i.test(raw)) return undefined
  if (URL_FORBIDDEN_CHARACTERS.test(raw)) return undefined
  return raw
}

function buildResult(fields) {
  const url = usableUrl(fields.url)
  if (!url) return undefined
  const title = collapseWhitespace(asText(fields.title)).slice(0, MAX_TITLE_LENGTH)
  const snippet = collapseWhitespace(asText(fields.snippet)).slice(0, MAX_SNIPPET_LENGTH)
  const publishedDate = collapseWhitespace(asText(fields.publishedDate)).slice(0, MAX_DATE_LENGTH)
  const result = { title: title || "(untitled)", url: url, snippet: snippet || "(no snippet)" }
  if (publishedDate) result.publishedDate = publishedDate
  return result
}

function extractRecords(provider, payload) {
  if (!isRecord(payload)) return []
  if (provider === "exa" || provider === "parallel") {
    return Array.isArray(payload.results) ? payload.results : []
  }
  if (provider === "serper") {
    return Array.isArray(payload.organic) ? payload.organic : []
  }
  if (provider !== "firecrawl") {
    throw new Error("Unsupported search provider: " + provider)
  }
  const data = payload.data
  if (Array.isArray(data)) return data
  if (!isRecord(data)) return []
  return Object.values(data).flatMap((value) => (Array.isArray(value) ? value : []))
}

function normalizeRecords(provider, records, limit) {
  const results = []
  for (const record of records) {
    if (results.length >= limit) break
    if (!isRecord(record)) continue
    let built
    if (provider === "exa") {
      built = buildResult({
        title: record.title,
        url: record.url,
        snippet: firstText(record.text, record.summary, record.highlights),
        publishedDate: record.publishedDate,
      })
    } else if (provider === "serper") {
      built = buildResult({
        title: record.title,
        url: firstText(record.link, record.url),
        snippet: record.snippet,
        publishedDate: record.date,
      })
    } else if (provider === "parallel") {
      built = buildResult({
        title: record.title,
        url: record.url,
        snippet: firstText(record.excerpts),
        publishedDate: firstText(record.publish_date, record.publishedDate),
      })
    } else if (provider === "firecrawl") {
      built = buildResult({
        title: record.title,
        url: record.url,
        snippet: firstText(record.description, record.snippet),
      })
    } else {
      // Never the trailing else: an unmirrored provider would otherwise be normalized with
      // Firecrawl's field names and quietly return nothing.
      throw new Error("Unsupported search provider: " + provider)
    }
    if (built) results.push(built)
  }
  return results
}

function serializeEnvelope(results) {
  const kept = results.slice()
  for (;;) {
    const envelope =
      kept.length === 0
        ? { results: [], message: NO_RESULTS_MESSAGE }
        : kept.length < results.length
          ? { results: kept, message: TRUNCATED_MESSAGE }
          : { results: kept }
    const serialized = JSON.stringify(envelope)
    if (kept.length === 0 || new TextEncoder().encode(serialized).length <= MAX_ENVELOPE_BYTES) {
      return serialized
    }
    kept.pop()
  }
}

async function readBoundedText(response) {
  const reader = response.body && response.body.getReader ? response.body.getReader() : undefined
  if (!reader) return await response.text()
  const chunks = []
  let total = 0
  for (;;) {
    const chunk = await reader.read()
    if (chunk.done) break
    total += chunk.value.byteLength
    if (total > MAX_RESPONSE_BYTES) {
      await reader.cancel()
      throw new Error("Search response exceeded the size limit")
    }
    chunks.push(chunk.value)
  }
  return Buffer.concat(chunks).toString("utf8")
}

export default function (pi) {
  const provider = process.env.${PI_SEARCH_PROVIDER_ENV_VAR}
  const apiKey = process.env.${PI_SEARCH_API_KEY_ENV_VAR}
  if (!provider || !apiKey) {
    throw new Error("Sim search extension requires ${PI_SEARCH_PROVIDER_ENV_VAR} and ${PI_SEARCH_API_KEY_ENV_VAR}")
  }
  const label = PROVIDER_LABELS[provider]
  if (!label) {
    throw new Error("Unsupported search provider: " + provider)
  }

  // Per extension load, which the CLI does once per invocation — same ceiling as the host adapter.
  let calls = 0

  pi.registerTool({
    name: TOOL_NAME,
    label: "Web Search",
    description: ${JSON.stringify(PI_SEARCH_TOOL_DESCRIPTION)},
    promptGuidelines: ${JSON.stringify(PI_SEARCH_PROMPT_GUIDELINES)},
    parameters: ${JSON.stringify(PI_SEARCH_TOOL_PARAMETERS)},
    async execute(_toolCallId, params, signal) {
      const rawQuery = params && typeof params.query === "string" ? params.query.trim() : ""
      if (!rawQuery) throw new Error("query is required")
      const query = rawQuery.slice(0, MAX_QUERY_LENGTH)
      const rawCount = params ? params.numResults : undefined
      const parsedCount =
        typeof rawCount === "number"
          ? rawCount
          : typeof rawCount === "string" && rawCount.trim()
            ? Number(rawCount)
            : Number.NaN
      const numResults = Number.isFinite(parsedCount)
        ? Math.min(MAX_RESULTS, Math.max(MIN_RESULTS, Math.floor(parsedCount)))
        : DEFAULT_RESULTS

      calls += 1
      if (calls > MAX_CALLS_PER_RUN) {
        throw new Error(BUDGET_MESSAGE)
      }

      const request = buildRequest(provider, apiKey, query, numResults)

      // Plain controller plumbing rather than AbortSignal.any, whose availability depends on the
      // Node version inside the sandbox image.
      const controller = new AbortController()
      let timedOut = false
      const timer = setTimeout(() => {
        timedOut = true
        controller.abort()
      }, TIMEOUT_MS)
      const onAbort = () => controller.abort()
      if (signal) signal.addEventListener("abort", onAbort, { once: true })

      let text
      try {
        let response
        try {
          response = await fetch(request.url, {
            method: "POST",
            headers: request.headers,
            body: JSON.stringify(request.body),
            signal: controller.signal,
          })
        } catch (error) {
          // Never surface the transport error verbatim: it can quote the request, and the request
          // carries the API key in a header. Only the shape of the failure is named, so a timeout
          // does not send the agent off to check a key that is fine.
          if (timedOut) {
            throw new Error(label + " search timed out after " + TIMEOUT_MS / 1000 + " seconds. Try a narrower query.")
          }
          throw new Error(label + " search could not reach the provider.")
        }

        if (response.status === 401 || response.status === 403) {
          throw new Error(
            label + " search was rejected as unauthorized. Check that the " + label + " API key is valid and has search access."
          )
        }
        if (response.status === 429) {
          throw new Error(
            label + " search was rate limited. Wait before searching again or reduce how often you search."
          )
        }
        if (!response.ok) {
          throw new Error(label + " search failed with HTTP " + response.status + ".")
        }

        text = await readBoundedText(response)
      } finally {
        clearTimeout(timer)
        if (signal) signal.removeEventListener("abort", onAbort)
      }

      let payload
      try {
        payload = JSON.parse(text)
      } catch (error) {
        throw new Error(label + " search returned a response that is not valid JSON.")
      }

      return {
        content: [
          { type: "text", text: serializeEnvelope(normalizeRecords(provider, extractRecords(provider, payload), numResults)) },
        ],
        details: {},
      }
    },
  })
}
`
