import { ClipboardList, Table } from '@sim/emcn/icons'
import { CirclebackIcon } from '@/components/icons'
import { AuthMode, type BlockConfig, type BlockMeta, IntegrationType } from '@/blocks/types'
import { getTrigger } from '@/triggers'

export const CirclebackBlock: BlockConfig = {
  type: 'circleback',
  name: 'Circleback',
  description: 'AI-powered meeting notes, action items, and transcripts',
  longDescription:
    'Integrate Circleback into your workflow to read meetings, notes, transcripts, and insights, search across meetings, manage action items and tags, and browse the people and companies you meet with. Circleback can also trigger workflows when meetings are processed.',
  category: 'tools',
  integrationType: IntegrationType.AI,
  bgColor: 'linear-gradient(180deg, #E0F7FA 0%, #FFFFFF 100%)',
  docsLink: 'https://docs.sim.ai/integrations/circleback',
  icon: CirclebackIcon,
  authMode: AuthMode.ApiKey,
  triggerAllowed: true,
  canvasPresentation: {
    defaultTitle: 'Circleback',
    sentences: {
      byOperation: {
        list_meetings: ['List meetings', { text: 'with ownership', field: 'ownership' }],
        get_meeting: [{ text: 'Read meeting', field: 'meetingId', core: true }],
        search_meetings: [{ text: 'Search meetings for', field: 'searchTerm', core: true }],
        get_transcript: [
          { text: 'Read the transcript of meeting', field: 'meetingId', core: true },
        ],
        update_meeting: [{ text: 'Update meeting', field: 'meetingId', core: true }],
        delete_meeting: [{ text: 'Delete meeting', field: 'meetingId', core: true }],
        list_action_items: [
          'List action items',
          { text: 'assigned to', field: 'assigneeType' },
          { text: 'with status', field: 'statusFilter' },
        ],
        update_action_item: [{ text: 'Update action item', field: 'actionItemId', core: true }],
        delete_action_item: [{ text: 'Delete action item', field: 'actionItemId', core: true }],
        list_calendar_events: ['List upcoming calendar events'],
        list_companies: ['List companies'],
        get_company: [{ text: 'Read company', field: 'domain', core: true }],
        list_people: ['List people', { text: 'at', field: 'domains' }],
        get_person: [{ text: 'Read person', field: 'profileId', core: true }],
        list_tags: ['List tags'],
        create_tag: [{ text: 'Create tag', field: 'tagName', core: true }],
        update_tag: [{ text: 'Update tag', field: 'tagId', core: true }],
        delete_tag: [{ text: 'Delete tag', field: 'tagId', core: true }],
        add_tag_to_meetings: [{ text: 'Add tag', field: 'tagId', core: true }, 'to meetings'],
        remove_tag_from_meetings: [
          { text: 'Remove tag', field: 'tagId', core: true },
          'from meetings',
        ],
      },
    },
  },

  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        { label: 'List Meetings', id: 'list_meetings' },
        { label: 'Get Meeting', id: 'get_meeting' },
        { label: 'Search Meetings', id: 'search_meetings' },
        { label: 'Get Transcript', id: 'get_transcript' },
        { label: 'Update Meeting', id: 'update_meeting' },
        { label: 'Delete Meeting', id: 'delete_meeting' },
        { label: 'List Action Items', id: 'list_action_items' },
        { label: 'Update Action Item', id: 'update_action_item' },
        { label: 'Delete Action Item', id: 'delete_action_item' },
        { label: 'List Calendar Events', id: 'list_calendar_events' },
        { label: 'List Companies', id: 'list_companies' },
        { label: 'Get Company', id: 'get_company' },
        { label: 'List People', id: 'list_people' },
        { label: 'Get Person', id: 'get_person' },
        { label: 'List Tags', id: 'list_tags' },
        { label: 'Create Tag', id: 'create_tag' },
        { label: 'Update Tag', id: 'update_tag' },
        { label: 'Delete Tag', id: 'delete_tag' },
        { label: 'Add Tag to Meetings', id: 'add_tag_to_meetings' },
        { label: 'Remove Tag from Meetings', id: 'remove_tag_from_meetings' },
      ],
      value: () => 'list_meetings',
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      required: true,
      placeholder: 'Enter your Circleback API key (cb_...)',
      password: true,
      description: 'Create an API key in Circleback under Settings then API keys.',
    },
    {
      id: 'meetingId',
      title: 'Meeting ID',
      type: 'short-input',
      required: {
        field: 'operation',
        value: ['get_meeting', 'get_transcript', 'update_meeting', 'delete_meeting'],
      },
      placeholder: 'e.g., abc123',
      condition: {
        field: 'operation',
        value: ['get_meeting', 'get_transcript', 'update_meeting', 'delete_meeting'],
      },
    },
    {
      id: 'name',
      title: 'Meeting Name',
      type: 'short-input',
      placeholder: 'New meeting name (leave blank to keep)',
      condition: { field: 'operation', value: 'update_meeting' },
    },
    {
      id: 'notes',
      title: 'Notes',
      type: 'long-input',
      placeholder: 'New meeting notes in Markdown (leave blank to keep)',
      condition: { field: 'operation', value: 'update_meeting' },
    },
    {
      id: 'privateNotes',
      title: 'Private Notes',
      type: 'long-input',
      placeholder: 'Your private notes for the meeting (leave blank to keep)',
      condition: { field: 'operation', value: 'update_meeting' },
      mode: 'advanced',
    },
    {
      id: 'searchTerm',
      title: 'Search Term',
      type: 'short-input',
      placeholder: 'Text to search for across meeting names and content',
      condition: { field: 'operation', value: 'search_meetings' },
    },
    {
      id: 'ownership',
      title: 'Ownership',
      type: 'dropdown',
      options: [
        { label: 'Mine', id: 'Mine' },
        { label: 'All', id: 'All' },
        { label: 'Shared', id: 'Shared' },
      ],
      value: () => 'Mine',
      condition: { field: 'operation', value: 'list_meetings' },
      mode: 'advanced',
    },
    {
      id: 'statuses',
      title: 'Statuses',
      type: 'short-input',
      placeholder: 'Comma-separated meeting statuses',
      condition: { field: 'operation', value: 'list_meetings' },
      mode: 'advanced',
    },
    {
      id: 'meetingIds',
      title: 'Meeting IDs',
      type: 'short-input',
      placeholder: 'Comma-separated meeting IDs',
      description: 'The meetings to add the tag to or remove it from.',
      condition: {
        field: 'operation',
        value: ['add_tag_to_meetings', 'remove_tag_from_meetings'],
      },
    },
    {
      id: 'searchMeetingIds',
      title: 'Meeting IDs',
      type: 'short-input',
      placeholder: 'Comma-separated meeting IDs',
      description: 'Restrict the search to these meetings.',
      condition: { field: 'operation', value: 'search_meetings' },
      mode: 'advanced',
    },
    {
      id: 'tagIds',
      title: 'Tag IDs',
      type: 'short-input',
      placeholder: 'Comma-separated tag IDs to filter by',
      condition: {
        field: 'operation',
        value: [
          'list_meetings',
          'search_meetings',
          'list_action_items',
          'list_companies',
          'list_people',
        ],
      },
      mode: 'advanced',
    },
    {
      id: 'attendeeProfileIds',
      title: 'Attendee Profile IDs',
      type: 'short-input',
      placeholder: 'Comma-separated attendee profile IDs to filter by',
      condition: {
        field: 'operation',
        value: ['list_meetings', 'search_meetings', 'list_action_items'],
      },
      mode: 'advanced',
    },
    {
      id: 'assigneeType',
      title: 'Assignee Scope',
      type: 'dropdown',
      options: [
        { label: 'Me', id: 'Me' },
        { label: 'Not Me', id: 'NotMe' },
        { label: 'Specific Profile', id: 'Profile' },
        { label: 'My Workspace', id: 'MyWorkspace' },
        { label: 'Outside My Workspace', id: 'OutsideMyWorkspace' },
        { label: 'Unassigned', id: 'Unassigned' },
        { label: 'Anyone', id: 'Anyone' },
      ],
      value: () => 'Me',
      condition: { field: 'operation', value: 'list_action_items' },
      mode: 'advanced',
    },
    {
      id: 'assigneeProfileId',
      title: 'Assignee Profile ID',
      type: 'short-input',
      placeholder: 'e.g., 42',
      description:
        'The profile to assign the action item to, or the literal text null to remove the assignee.',
      condition: { field: 'operation', value: 'update_action_item' },
      mode: 'advanced',
    },
    {
      id: 'assigneeFilterProfileId',
      title: 'Assignee Profile ID',
      type: 'short-input',
      placeholder: 'e.g., 42',
      description: 'Only return action items assigned to this profile.',
      condition: { field: 'operation', value: 'list_action_items' },
      mode: 'advanced',
    },
    {
      id: 'assigneeTeamId',
      title: 'Assignee Team ID',
      type: 'short-input',
      placeholder: 'e.g., 7',
      condition: { field: 'operation', value: 'list_action_items' },
      mode: 'advanced',
    },
    {
      id: 'status',
      title: 'Status',
      type: 'dropdown',
      options: [
        { label: 'Leave unchanged', id: '' },
        { label: 'Pending', id: 'PENDING' },
        { label: 'Done', id: 'DONE' },
      ],
      value: () => '',
      description: 'The completion status to set on the action item.',
      condition: { field: 'operation', value: 'update_action_item' },
    },
    {
      id: 'statusFilter',
      title: 'Status',
      type: 'dropdown',
      options: [
        { label: 'Default (incomplete)', id: '' },
        { label: 'Pending', id: 'PENDING' },
        { label: 'Done', id: 'DONE' },
      ],
      value: () => '',
      description: 'The completion status to filter by. Defaults to incomplete action items.',
      condition: { field: 'operation', value: 'list_action_items' },
      mode: 'advanced',
    },
    {
      id: 'actionItemId',
      title: 'Action Item ID',
      type: 'short-input',
      required: { field: 'operation', value: ['update_action_item', 'delete_action_item'] },
      placeholder: 'e.g., 123',
      condition: { field: 'operation', value: ['update_action_item', 'delete_action_item'] },
    },
    {
      id: 'title',
      title: 'Action Item Title',
      type: 'short-input',
      placeholder: 'New title (leave blank to keep)',
      condition: { field: 'operation', value: 'update_action_item' },
    },
    {
      id: 'description',
      title: 'Action Item Description',
      type: 'long-input',
      placeholder: 'New description (leave blank to keep)',
      condition: { field: 'operation', value: 'update_action_item' },
    },
    {
      id: 'startTimeLookbackHours',
      title: 'Lookback Hours',
      type: 'short-input',
      placeholder: 'e.g., 24',
      description: 'How many hours in the past to include calendar meetings from.',
      condition: { field: 'operation', value: 'list_calendar_events' },
      mode: 'advanced',
    },
    {
      id: 'startTimeLookaheadHours',
      title: 'Lookahead Hours',
      type: 'short-input',
      placeholder: 'e.g., 168',
      description: 'How many hours in the future to include calendar meetings from.',
      condition: { field: 'operation', value: 'list_calendar_events' },
      mode: 'advanced',
    },
    {
      id: 'sortDirection',
      title: 'Sort Direction',
      type: 'dropdown',
      options: [
        { label: 'Ascending', id: 'ascending' },
        { label: 'Descending', id: 'descending' },
      ],
      value: () => 'ascending',
      condition: { field: 'operation', value: 'list_calendar_events' },
      mode: 'advanced',
    },
    {
      id: 'includeOfflineSingleAttendee',
      title: 'Include Offline Single-Attendee Meetings',
      type: 'dropdown',
      options: [
        { label: 'No', id: 'false' },
        { label: 'Yes', id: 'true' },
      ],
      value: () => 'false',
      description: 'Include calendar meetings that have no meeting link and only one attendee.',
      condition: { field: 'operation', value: 'list_calendar_events' },
      mode: 'advanced',
    },
    {
      id: 'domain',
      title: 'Company Domain',
      type: 'short-input',
      required: { field: 'operation', value: 'get_company' },
      placeholder: 'e.g., example.com',
      condition: { field: 'operation', value: 'get_company' },
    },
    {
      id: 'domains',
      title: 'Company Domains',
      type: 'short-input',
      placeholder: 'Comma-separated company domains to filter by',
      condition: { field: 'operation', value: 'list_people' },
      mode: 'advanced',
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      placeholder: 'Maximum number of people to return',
      condition: { field: 'operation', value: 'list_people' },
      mode: 'advanced',
    },
    {
      id: 'profileId',
      title: 'Profile ID',
      type: 'short-input',
      required: { field: 'operation', value: 'get_person' },
      placeholder: 'e.g., 42',
      condition: { field: 'operation', value: 'get_person' },
    },
    {
      id: 'tagId',
      title: 'Tag ID',
      type: 'short-input',
      required: {
        field: 'operation',
        value: ['update_tag', 'delete_tag', 'add_tag_to_meetings', 'remove_tag_from_meetings'],
      },
      placeholder: 'e.g., 5',
      condition: {
        field: 'operation',
        value: ['update_tag', 'delete_tag', 'add_tag_to_meetings', 'remove_tag_from_meetings'],
      },
    },
    {
      id: 'tagName',
      title: 'Tag Name',
      type: 'short-input',
      required: { field: 'operation', value: 'create_tag' },
      placeholder: 'e.g., Customer Interview',
      condition: { field: 'operation', value: ['create_tag', 'update_tag'] },
    },
    {
      id: 'tagDescription',
      title: 'Tag Description',
      type: 'short-input',
      placeholder: 'What this tag is for',
      condition: { field: 'operation', value: ['create_tag', 'update_tag'] },
      mode: 'advanced',
    },
    {
      id: 'cursor',
      title: 'Cursor',
      type: 'short-input',
      placeholder: 'Pagination cursor from previous response',
      condition: {
        field: 'operation',
        value: [
          'list_meetings',
          'search_meetings',
          'list_action_items',
          'list_calendar_events',
          'list_companies',
          'list_people',
        ],
      },
      mode: 'advanced',
    },
    ...getTrigger('circleback_meeting_completed').subBlocks,
    ...getTrigger('circleback_meeting_notes').subBlocks,
    ...getTrigger('circleback_webhook').subBlocks,
  ],

  tools: {
    access: [
      'circleback_list_meetings',
      'circleback_get_meeting',
      'circleback_search_meetings',
      'circleback_get_transcript',
      'circleback_update_meeting',
      'circleback_delete_meeting',
      'circleback_list_action_items',
      'circleback_update_action_item',
      'circleback_delete_action_item',
      'circleback_list_calendar_events',
      'circleback_list_companies',
      'circleback_get_company',
      'circleback_list_people',
      'circleback_get_person',
      'circleback_list_tags',
      'circleback_create_tag',
      'circleback_update_tag',
      'circleback_delete_tag',
      'circleback_add_tag_to_meetings',
      'circleback_remove_tag_from_meetings',
    ],
    config: {
      tool: (params) => `circleback_${params.operation}`,
      params: (params) => {
        /* Filter variants live on their own subBlocks so an operation switch
           cannot leak a mutation input into a list filter; remap them onto the
           tool param names here. */
        const result: Record<string, unknown> = {}
        if (params.operation === 'list_action_items') {
          if (params.statusFilter) result.status = params.statusFilter
          if (params.assigneeFilterProfileId) {
            result.assigneeProfileId = params.assigneeFilterProfileId
          }
        }
        if (params.operation === 'search_meetings' && params.searchMeetingIds) {
          result.meetingIds = params.searchMeetingIds
        }
        return result
      },
    },
  },

  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    apiKey: { type: 'string', description: 'Circleback API key' },
    meetingId: { type: 'string', description: 'Meeting ID' },
    name: { type: 'string', description: 'New meeting name' },
    notes: { type: 'string', description: 'New meeting notes in Markdown' },
    privateNotes: { type: 'string', description: 'Private notes for the meeting' },
    searchTerm: { type: 'string', description: 'Text to search for across meetings' },
    ownership: { type: 'string', description: 'Which meetings to list: All, Mine, or Shared' },
    statuses: { type: 'string', description: 'Comma-separated meeting statuses to filter by' },
    meetingIds: {
      type: 'string',
      description: 'Comma-separated IDs of the meetings to add the tag to or remove it from',
    },
    searchMeetingIds: {
      type: 'string',
      description: 'Comma-separated meeting IDs to restrict the search to',
    },
    tagIds: { type: 'string', description: 'Comma-separated tag IDs to filter by' },
    attendeeProfileIds: {
      type: 'string',
      description: 'Comma-separated attendee profile IDs to filter by',
    },
    assigneeType: { type: 'string', description: 'Assignee scope filter for action items' },
    assigneeProfileId: {
      type: 'string',
      description: 'Profile to assign the action item to, or null to remove the assignee',
    },
    assigneeFilterProfileId: {
      type: 'string',
      description: 'Only return action items assigned to this profile',
    },
    assigneeTeamId: { type: 'string', description: 'Assignee team ID to filter by' },
    status: { type: 'string', description: 'The completion status to set, PENDING or DONE' },
    statusFilter: {
      type: 'string',
      description: 'The completion status to filter by, PENDING or DONE',
    },
    actionItemId: { type: 'string', description: 'Action item ID' },
    title: { type: 'string', description: 'New action item title' },
    description: { type: 'string', description: 'New action item description' },
    startTimeLookbackHours: {
      type: 'string',
      description: 'Hours in the past to include calendar meetings from',
    },
    startTimeLookaheadHours: {
      type: 'string',
      description: 'Hours in the future to include calendar meetings from',
    },
    sortDirection: {
      type: 'string',
      description: 'Calendar event sort direction, ascending or descending',
    },
    includeOfflineSingleAttendee: {
      type: 'string',
      description: 'Whether to include meetings with no link and one attendee',
    },
    domain: { type: 'string', description: 'Company domain to fetch' },
    domains: { type: 'string', description: 'Comma-separated company domains to filter people by' },
    limit: { type: 'string', description: 'Maximum number of people to return' },
    profileId: { type: 'string', description: 'Person profile ID' },
    tagId: { type: 'string', description: 'Tag ID' },
    tagName: { type: 'string', description: 'Tag display name' },
    tagDescription: { type: 'string', description: 'Tag description' },
    cursor: { type: 'string', description: 'Pagination cursor' },
  },

  outputs: {
    id: {
      type: 'any',
      description:
        'The ID of the returned resource: a string for meetings, a number for action items, people, and tags, or the numeric meeting ID from a trigger payload',
    },
    name: { type: 'string', description: 'Meeting or tag name' },
    url: { type: 'string', description: 'Virtual meeting URL (Zoom, Meet, Teams)' },
    createdAt: { type: 'string', description: 'Creation timestamp (ISO 8601)' },
    updatedAt: { type: 'string', description: 'Last update timestamp (ISO 8601)' },
    duration: { type: 'number', description: 'Duration in seconds' },
    recordingUrl: { type: 'string', description: 'Recording URL (valid 24 hours)' },
    tags: {
      type: 'json',
      description: 'Tags on the meeting, or the workspace tag listing (id, name, description)',
    },
    icalUid: { type: 'string', description: 'Calendar event ID' },
    attendees: { type: 'json', description: 'Array of attendee objects' },
    notes: { type: 'string', description: 'Meeting notes in Markdown' },
    privateNotes: { type: 'string', description: 'The authenticated user private notes' },
    actionItems: { type: 'json', description: 'Array of action items' },
    transcript: {
      type: 'json',
      description: 'Array of transcript segments (speaker, text, timestamp)',
    },
    insights: { type: 'json', description: 'User-created insights keyed by insight name' },
    linkAccess: {
      type: 'string',
      description: 'Who can access the meeting through its shareable link',
    },
    calendarEvent: { type: 'json', description: 'The calendar event associated with a meeting' },
    meetings: {
      type: 'json',
      description: 'Meetings returned by list, search, and tag operations',
    },
    nextCursor: { type: 'string', description: 'Pagination cursor for the next page' },
    hasMore: { type: 'boolean', description: 'Whether another page is available' },
    events: { type: 'json', description: 'Upcoming calendar events' },
    companies: { type: 'json', description: 'Companies (id, name, avatarUrl, domain)' },
    people: { type: 'json', description: 'People (id, firstName, lastName, email, companyName)' },
    externalLinks: {
      type: 'json',
      description: 'Links to a person or company on external platforms',
    },
    domain: { type: 'string', description: 'Company website domain' },
    avatarUrl: { type: 'string', description: 'Company logo URL' },
    title: { type: 'string', description: 'Action item title, or a person job title' },
    description: { type: 'string', description: 'Action item or tag description' },
    assignee: { type: 'json', description: 'Action item assignee, or null if unassigned' },
    completedAt: { type: 'string', description: 'When an action item was marked done' },
    meetingId: { type: 'string', description: 'The meeting an action item belongs to' },
    status: { type: 'string', description: 'The completion status to set, PENDING or DONE' },
    statusFilter: {
      type: 'string',
      description: 'The completion status to filter by, PENDING or DONE',
    },
    companyId: { type: 'number', description: 'The company a person belongs to' },
    companyName: { type: 'string', description: 'The company name of a person' },
    email: { type: 'string', description: 'A person email address' },
    firstName: { type: 'string', description: 'A person first name' },
    lastName: { type: 'string', description: 'A person last name' },
    meeting: { type: 'json', description: 'Full meeting payload from a trigger' },
  },

  triggers: {
    enabled: true,
    available: ['circleback_meeting_completed', 'circleback_meeting_notes', 'circleback_webhook'],
  },
}

export const CirclebackBlockMeta = {
  tags: ['meeting', 'note-taking'],
  url: 'https://circleback.ai',
  templates: [
    {
      icon: CirclebackIcon,
      title: 'Circleback recap to Slack',
      prompt:
        'Build a workflow that triggers when a meeting is processed in Circleback, takes the notes and action items from the payload, and posts a clean recap to the relevant Slack channel.',
      modules: ['agent', 'workflows'],
      category: 'productivity',
      tags: ['meeting', 'automation'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: ClipboardList,
      title: 'Circleback action-item tracker',
      prompt:
        'Create a workflow that triggers when a Circleback meeting is processed, reads the action items from the payload, and writes each one to a tasks table with the owner and due date.',
      modules: ['tables', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['meeting', 'automation'],
    },
    {
      icon: Table,
      title: 'Circleback notes to Notion',
      prompt:
        'Build a workflow that triggers when a meeting is processed in Circleback, pulls the notes, attendees, and transcript from the payload, and writes a structured meeting note to Notion with next steps.',
      modules: ['agent', 'workflows'],
      category: 'productivity',
      tags: ['meeting', 'note-taking'],
      alsoIntegrations: ['notion'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback meeting prep brief',
      prompt:
        'Build a scheduled workflow that lists upcoming calendar events from Circleback each morning, pulls past meetings and notes for the same attendees, and posts a prep brief for each external meeting to Slack.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['meeting', 'research'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback action-item chaser',
      prompt:
        'Create a scheduled workflow that lists pending Circleback action items across the workspace each week, groups them by assignee, and sends each owner a summary of what is still open.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['team', 'automation'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback CRM updater',
      prompt:
        'Build a workflow that runs after a Circleback sales meeting, gets the full meeting with notes and insights, summarizes it into a deal-ready update, and writes it to the matching HubSpot or Salesforce record using the attendee company domain.',
      modules: ['agent', 'workflows'],
      category: 'sales',
      tags: ['sales', 'crm'],
      alsoIntegrations: ['hubspot', 'salesforce'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback customer-voice miner',
      prompt:
        'Create a workflow that searches Circleback meetings for a product or feature keyword, reads the matching transcripts, extracts notable customer quotes and pain points, and writes them to a tables-based research log.',
      modules: ['tables', 'agent', 'workflows'],
      category: 'marketing',
      tags: ['marketing', 'research'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback weekly meeting digest',
      prompt:
        'Build a scheduled weekly workflow that lists the past week of Circleback meetings, aggregates decisions, action items, and recurring themes, and posts a digest to the team Slack channel.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'productivity',
      tags: ['team', 'reporting'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: CirclebackIcon,
      title: 'Circleback tag janitor',
      prompt:
        'Create a workflow that lists Circleback meetings without tags, classifies each meeting from its name and attendees, and applies the right existing tag so meetings stay organized.',
      modules: ['agent', 'workflows'],
      category: 'operations',
      tags: ['automation'],
    },
  ],
  skills: [
    {
      name: 'digest-meetings',
      description:
        'List recent Circleback meetings and produce a structured digest of notes, decisions, and action items.',
      content:
        '# Digest Meetings\n\nTurn recent Circleback meetings into a concise digest.\n\n## Steps\n1. List meetings, optionally filtered by tags or attendees.\n2. For each meeting, get the full meeting to read notes, action items, and insights.\n3. Extract the meeting title, key decisions, takeaways, and action items with owners.\n4. Keep each meeting summary short and uniformly structured.\n\n## Output\nReturn a digest with one section per meeting: title, date, decisions, takeaways, and action items. Suitable for a team recap or daily summary.',
    },
    {
      name: 'chase-action-items',
      description: 'List open Circleback action items and group them by assignee for follow-up.',
      content:
        '# Chase Action Items\n\nBuild a follow-up list from open action items.\n\n## Steps\n1. List action items with the assignee scope set to Anyone and the default incomplete status.\n2. Group items by assignee, noting the source meeting for each.\n3. Flag items whose source meeting is more than a week old.\n\n## Output\nReturn a per-assignee list of open action items, each with the task, source meeting, and age. Ready to send as reminders.',
    },
    {
      name: 'research-relationship',
      description:
        'Pull the meeting history, people, and notes Circleback holds for a company before an important call.',
      content:
        '# Research Relationship\n\nAssemble the relationship history with a company.\n\n## Steps\n1. Get the company by domain to find its people and external links.\n2. Search meetings restricted to those attendee profiles.\n3. Get the most relevant meetings and read their notes and insights.\n\n## Output\nReturn a brief with the people met, meeting timeline, open action items, and key discussion themes for the company.',
    },
  ],
} as const satisfies BlockMeta
