apiVersion: v2
name: sim
description: A Helm chart for Sim - the open-source AI workspace where teams build, deploy, and manage AI agents
type: application
version: 1.9.0
appVersion: "v0.8.18"
kubeVersion: ">=1.25.0-0"
home: https://sim.ai
icon: https://raw.githubusercontent.com/simstudioai/sim/main/apps/sim/public/logo/primary/primary.svg
sources:
  - https://github.com/simstudioai/sim
maintainers:
  - name: Sim Team
    email: help@sim.ai
    url: https://sim.ai
keywords:
  - ai
  - workflow
  - automation
  - agents
  - nextjs
annotations:
  category: developer-tools
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Homepage
      url: https://sim.ai
    - name: Documentation
      url: https://docs.sim.ai
    - name: Source
      url: https://github.com/simstudioai/sim
    - name: Slack
      url: https://join.slack.com/t/sim-ott9864/shared_invite/zt-43lp8tc5v-0qrrqHGBKUsvQlpoouH~TA
