#!/usr/bin/env bun
/**
 * Generates the access-control successor map from the block registry.
 *
 * The map answers one question — "which block type is an allowlist decision
 * about this id really made against?" — and it has to be answerable from
 * `lib/permission-groups/`, which `scripts/check-application-graph.ts` forbids
 * from importing `blocks/`: the authorization funnel would pull every block
 * definition into every surface that authorizes anything. Before this file the
 * answer was reachable only through `getBlock`, so the env allowlist was
 * intersected with the group allowlist *textually*, and a deployment naming
 * `slack` against a group naming `slack_v2` intersected to nothing — refusing an
 * integration both policies allow.
 *
 * Entries are flattened to the terminal successor; see {@link flattenSuccessors}
 * for the walk and its stopping rules.
 *
 * Usage:
 *   bun run scripts/generate-block-successors.ts
 *   bun run scripts/generate-block-successors.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { formatGeneratedSource } from './format-generated-source'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, '..')
const OUTPUT_PATH = resolve(ROOT, 'apps/sim/lib/permission-groups/block-successors.generated.ts')
const CHECK_MODE = process.argv.includes('--check')

interface SunsetBlock {
  sunset?: { status: string; replacedBy?: string }
}

/**
 * The block registry, loaded lazily.
 *
 * A static import would run on every import of this module, including the unit
 * test for {@link flattenSuccessors}, which needs no registry and cannot
 * resolve the `@/` specifiers every block file uses from the repo-root vitest
 * project.
 */
async function loadRegistry(): Promise<Record<string, SunsetBlock>> {
  const { BLOCK_REGISTRY } = await import('../apps/sim/blocks/registry-maps')
  return BLOCK_REGISTRY as unknown as Record<string, SunsetBlock>
}

/**
 * Flattens one-hop `replacedBy` edges to terminal successors.
 *
 * Reproduces the walk the runtime used to perform against the registry, with
 * both of its stopping rules: a cycle stops at the last id visited rather than
 * spinning, and an edge naming an unregistered block is not followed, leaving
 * the id as its own answer. Only ids whose answer differs from themselves are
 * returned, so a lookup that misses is a block with no successor.
 */
export function flattenSuccessors(
  directSuccessors: Readonly<Record<string, string>>,
  isRegistered: (blockType: string) => boolean
): ReadonlyMap<string, string> {
  const terminal = (blockType: string): string => {
    const seen = new Set<string>([blockType])
    let current = blockType

    while (true) {
      const successor = directSuccessors[current]
      if (!successor || seen.has(successor) || !isRegistered(successor)) return current
      seen.add(successor)
      current = successor
    }
  }

  const successors = new Map<string, string>()
  for (const blockType of Object.keys(directSuccessors).sort()) {
    const resolved = terminal(blockType)
    if (resolved !== blockType) successors.set(blockType, resolved)
  }
  return successors
}

export async function buildBlockSuccessors(): Promise<ReadonlyMap<string, string>> {
  const registry = await loadRegistry()

  /** `getBlock`'s own-key lookup, with its dash-to-underscore normalization. */
  const lookup = (type: string): SunsetBlock | undefined => {
    if (Object.hasOwn(registry, type)) return registry[type]
    const normalized = type.replace(/-/g, '_')
    return Object.hasOwn(registry, normalized) ? registry[normalized] : undefined
  }

  const directSuccessors: Record<string, string> = {}
  for (const blockType of Object.keys(registry)) {
    const successor = registry[blockType]?.sunset?.replacedBy
    if (successor) directSuccessors[blockType] = successor
  }
  return flattenSuccessors(directSuccessors, (blockType) => lookup(blockType) !== undefined)
}

function render(successors: ReadonlyMap<string, string>): string {
  const quote = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const entries = [...successors]
    .map(
      ([blockType, successor]) =>
        `  ${/^[A-Za-z_$][\w$]*$/.test(blockType) ? blockType : quote(blockType)}: ${quote(successor)},`
    )
    .join('\n')

  return `/**
 * Generated by \`bun run generate:block-successors\` from the block registry.
 * Do not edit this file directly.
 *
 * Maps a retired block type to the *terminal* type an access-control decision
 * about it is made against — \`sunset.replacedBy\`, followed transitively. It
 * exists as a generated projection because \`lib/permission-groups/\` may not
 * import \`blocks/\`; see \`scripts/generate-block-successors.ts\`.
 */
export const BLOCK_ACCESS_SUCCESSORS: Record<string, string> = {
${entries}
}
`
}

async function main(): Promise<void> {
  const successors = await buildBlockSuccessors()

  /**
   * The map must be closed: no key may also be a value, or a lookup would need
   * a second hop and the runtime does exactly one. Flattening guarantees it, so
   * a violation means the flattening itself regressed.
   */
  for (const successor of successors.values()) {
    if (successors.has(successor)) {
      throw new Error(
        `Block successor map is not flattened: '${successor}' is both a successor and a retired id.`
      )
    }
  }

  const generated = formatGeneratedSource(render(successors), OUTPUT_PATH, ROOT)

  if (CHECK_MODE) {
    const current = await readFile(OUTPUT_PATH, 'utf8').catch(() => '')
    if (current !== generated) {
      console.error(
        'Block successor map is stale. Run `bun run generate:block-successors` and commit the result.'
      )
      process.exit(1)
    }
    process.stdout.write('Block successor map is current.\n')
    return
  }

  await writeFile(OUTPUT_PATH, generated)
  process.stdout.write(`Generated ${OUTPUT_PATH}\n`)
}

if (import.meta.main) await main()
