#!/usr/bin/env bun
/**
 * Generates deployment facts from the canonical OAuth registry.
 *
 * The setup package cannot import the application registry at runtime, so it
 * consumes this checked-in projection instead. Deployment policy does not
 * belong here; special availability rules remain handwritten in
 * `packages/deployment-config/src/service-account-metadata.ts`.
 *
 * Usage:
 *   bun run scripts/generate-deployment-config.ts
 *   bun run scripts/generate-deployment-config.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getAllOAuthServices } from '../apps/sim/lib/oauth/utils'
import integrationsJson from '../packages/deployment-config/src/integrations.json'

interface DeploymentIntegration {
  authType: 'oauth' | 'api-key' | 'none'
  oauthServiceId?: string
}

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, '..')
const OUTPUT_PATH = resolve(
  ROOT,
  'packages/deployment-config/src/service-account-providers.generated.ts'
)
const CHECK_MODE = process.argv.includes('--check')

function buildServiceAccountProviders(): ReadonlyMap<string, string> {
  const canonicalServices = new Map<string, string | undefined>()
  for (const service of getAllOAuthServices()) {
    if (canonicalServices.has(service.serviceId)) {
      throw new Error(`Duplicate canonical OAuth service id: ${service.serviceId}`)
    }
    canonicalServices.set(service.serviceId, service.serviceAccountProviderId)
  }

  const catalogServiceIds = new Set<string>()
  for (const integration of integrationsJson.integrations as readonly DeploymentIntegration[]) {
    if (integration.authType !== 'oauth') continue
    if (!integration.oauthServiceId) {
      throw new Error(
        'Generated integration catalog contains an OAuth entry without oauthServiceId'
      )
    }
    catalogServiceIds.add(integration.oauthServiceId)
  }

  const providers = new Map<string, string>()
  for (const serviceId of [...catalogServiceIds].sort()) {
    if (!canonicalServices.has(serviceId)) {
      throw new Error(`Integration catalog references unknown OAuth service: ${serviceId}`)
    }
    const providerId = canonicalServices.get(serviceId)
    if (providerId) providers.set(serviceId, providerId)
  }
  return providers
}

function renderServiceAccountProviders(providers: ReadonlyMap<string, string>): string {
  const quote = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const entries = [...providers]
    .map(
      ([serviceId, providerId]) =>
        `  ${/^[A-Za-z_$][\w$]*$/.test(serviceId) ? serviceId : quote(serviceId)}: ${quote(providerId)},`
    )
    .join('\n')

  return `/**
 * Generated by \`bun run deployment-config:generate\` from the canonical OAuth
 * registry and integration catalog. Do not edit this file directly.
 */
export const SERVICE_ACCOUNT_PROVIDER_BY_OAUTH_SERVICE_ID = {
${entries}
} as const
`
}

const generated = renderServiceAccountProviders(buildServiceAccountProviders())

if (CHECK_MODE) {
  const current = await readFile(OUTPUT_PATH, 'utf8').catch(() => '')
  if (current !== generated) {
    throw new Error(
      'Deployment config is stale. Run `bun run deployment-config:generate` and commit the result.'
    )
  }
  process.stdout.write('Deployment config is current.\n')
} else {
  await writeFile(OUTPUT_PATH, generated)
  process.stdout.write(`Generated ${OUTPUT_PATH}\n`)
}
