//! The Codewhale mark — the founder raster in braille dots (2×4 per cell).
//!
//! The rows are generated, never hand-drawn: `scripts/brand/braille-mark.py`
//! reads the canonical product mark (`brand/codewhalemarkfinal.png`, PRD
//! section 6: the white whale on the navy rounded square) and derives the
//! hero whale's navy darkness down to a dot grid (threshold 0.3, aspect
//! preserved and centred in the rung's box, all-blank edge columns trimmed,
//! the eye carved as one cleared dot). No redraws, no traced SVG: the dots
//! are a proportional derivative of the founder file. Two rungs from the
//! boxes: [`MarkSize::Small`] (box 11×3 → ink 7×3) and [`MarkSize::Tiny`]
//! (box 8×2 → ink 5×2). The ASCII lane has no mark at all:
//! `glyphs::ascii_fallback` flattens braille to `#`, so the wordmark line
//! stands alone there.
//!
//! Three paint tiers share one motion:
//!
//! - [`render_mark`] paints the braille rows (every terminal).
//! - On terminals that answer the kitty graphics query
//!   ([`probe_kitty_graphics`]) the launch header paints
//!   [`render_kitty_placeholders`] instead: Unicode placeholder cells the
//!   terminal replaces with the PNG transmitted once by
//!   [`transmit_kitty_mark`]. ratatui's buffer still owns the cells, so the
//!   image survives redraws.
//! - On terminals that draw sixel but not kitty ([`probe_sixel_graphics`])
//!   the header reserves the same block with [`render_sixel_reserve`] and
//!   the event loop emits the same PNG rasterised by [`sixel_mark_sequence`]
//!   over it, re-emitting only when the block moves. Anything else falls
//!   back to the braille tier: the default, never an empty block.
//!
//! Motion ("surfacing", founder 2026-09-01): over `MARK_SURFACE_MS` the mark
//! reveals from the bottom of its box upward — the whale rises out of the
//! field — while its colour lerps from the field to the accent through
//! [`surface_progress`]'s raised-cosine ease. Then it holds still forever.
//! Reduced motion passes `progress = 1.0`, which is this same drawing at its
//! endpoint, so the still frame cannot drift from the animated one. The
//! sixel tier does not animate: it shows the settled raster at once, which
//! is that same endpoint.

use std::io::Write;
use std::sync::OnceLock;

use ratatui::{buffer::Buffer, layout::Rect, style::Color, style::Style};

/// Rungs of the mark's scale ladder, each generated at its own box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkSize {
    /// Box 11×3, ink 7×3 — the launch header's mark.
    Small,
    /// Box 8×2, ink 5×2 — for stages too narrow for the header lines beside
    /// the small rung.
    Tiny,
}

// generated by scripts/brand/braille-mark.py from brand/codewhalemarkfinal.png
// (founder hero whale 504x453px, threshold 0.3, aspect preserved,
// edge columns trimmed, eye carved)

// SMALL: box 11x3 -> ink 7x3
const SMALL_ROWS: [&str; 3] = [
    "⢠⡶⠛⠧⠄  ", //
    "⣿⣄⣠⣤⣶⠶⠆",
    "⠘⠻⣿⣗⠡⠊ ",
];

// TINY: box 8x2 -> ink 5x2
const TINY_ROWS: [&str; 2] = [
    "⢠⡞⠛⢂⣀", //
    "⠘⠿⣿⠍⠉",
];

impl MarkSize {
    /// Cell footprint as `(cols, rows)` — the ink's, not the design box's.
    #[must_use]
    pub const fn cells(self) -> (u16, u16) {
        match self {
            Self::Small => (7, 3),
            Self::Tiny => (5, 2),
        }
    }

    /// The braille rows for this rung. Blank cells are spaces so the
    /// renderer leaves the field behind them untouched.
    #[must_use]
    pub const fn rows(self) -> &'static [&'static str] {
        match self {
            Self::Small => &SMALL_ROWS,
            Self::Tiny => &TINY_ROWS,
        }
    }
}

/// Blend `from` toward `to` (0.0 → `from`, 1.0 → `to`). At 0 the mark is
/// exactly the field colour, so it rises out of the water rather than over it.
#[must_use]
pub fn lerp_color(from: Color, to: Color, amount: f32) -> Color {
    let amount = amount.clamp(0.0, 1.0);
    match (from, to) {
        (Color::Rgb(fr, fg, fb), Color::Rgb(tr, tg, tb)) => Color::Rgb(
            lerp_channel(fr, tr, amount),
            lerp_channel(fg, tg, amount),
            lerp_channel(fb, tb, amount),
        ),
        // Indexed colours have no channels to interpolate; snap at midpoint.
        _ => {
            if amount >= 0.5 {
                to
            } else {
                from
            }
        }
    }
}

fn lerp_channel(from: u8, to: u8, amount: f32) -> u8 {
    let from = f32::from(from);
    let to = f32::from(to);
    (from + (to - from) * amount).round().clamp(0.0, 255.0) as u8
}

/// Raised-cosine rise over `duration_ms`, saturating at 1.0. Wall-clock keyed,
/// so a dropped frame costs smoothness, never correctness.
#[must_use]
pub fn surface_progress(elapsed_ms: u128, duration_ms: u128) -> f32 {
    if duration_ms == 0 || elapsed_ms >= duration_ms {
        return 1.0;
    }
    let t = elapsed_ms as f32 / duration_ms as f32;
    0.5 * (1.0 - (std::f32::consts::PI * t).cos())
}

/// Braille dot bits by dot row inside a cell (row 0 = top): dots 1/4, 2/5,
/// 3/6, then 7/8 on the bottom row.
const DOT_ROW_BITS: [u32; 4] = [0x01 | 0x08, 0x02 | 0x10, 0x04 | 0x20, 0x40 | 0x80];

/// The dot bits of a braille glyph; `None` for anything outside U+2800..=U+28FF.
fn braille_bits(glyph: char) -> Option<u32> {
    let code = u32::from(glyph);
    (0x2800..=0x28FF).contains(&code).then(|| code - 0x2800)
}

/// How many dot rows (from the bottom) of a `total`-dot-row mark are shown
/// at `progress`. `0.0` shows nothing, `1.0` shows every row; the reveal is
/// monotonic so a frame never un-surfaces.
fn revealed_dot_rows(progress: f32, total: u32) -> u32 {
    ((progress.clamp(0.0, 1.0) * total as f32).ceil() as u32).min(total)
}

/// Paint the braille mark with its top-left corner at `area`'s origin, in
/// `ink`, surfacing out of `field`. `progress` is `[0,1]`: the box reveals
/// dot row by dot row from the bottom while the colour lerps field → ink.
/// Returns the painted rect, or a zero-width rect when the area is too small
/// (the mark declines rather than clipping).
pub fn render_mark(
    area: Rect,
    buf: &mut Buffer,
    size: MarkSize,
    ink: Color,
    field: Color,
    progress: f32,
) -> Rect {
    let rows = size.rows();
    let (cols, row_count) = size.cells();
    if area.width < cols || area.height < row_count {
        return Rect::new(area.x, area.y, 0, 0);
    }
    let total_dot_rows = u32::from(row_count) * 4;
    let first_visible = total_dot_rows - revealed_dot_rows(progress, total_dot_rows);
    let color = lerp_color(field, ink, progress);
    for (index, line) in rows.iter().enumerate() {
        let y = area.y + index as u16;
        let mask = DOT_ROW_BITS
            .iter()
            .enumerate()
            .filter(|(dot_row, _)| (index as u32) * 4 + *dot_row as u32 >= first_visible)
            .fold(0u32, |mask, (_, bits)| mask | bits);
        if mask == 0 {
            continue;
        }
        for (x, glyph) in (area.x..).zip(line.chars()) {
            if x >= area.right() {
                break;
            }
            // Blanks (and fully-masked cells) are skipped, not painted: they
            // must not erase the field behind them.
            let bits = braille_bits(glyph).map_or(0, |bits| bits & mask);
            if bits == 0 {
                continue;
            }
            if let Some(cell) = buf.cell_mut((x, y)) {
                let glyph = char::from_u32(0x2800 | bits).expect("braille block is contiguous");
                cell.set_symbol(&glyph.to_string());
                cell.set_style(Style::default().fg(color));
            }
        }
    }
    Rect::new(area.x, area.y, cols, row_count)
}

// ---------------------------------------------------------------------------
// Kitty graphics tier.
//
// Protocol: https://sw.kovidgoyal.net/kitty/graphics-protocol/ — the image is
// transmitted once as base64 PNG chunks (`a=T,f=100`), given a *virtual*
// placement (`a=p,U=1`) sized in cells, and then shown wherever the screen
// holds placeholder cells: U+10EEEE with the image id in the foreground
// colour and the row/column encoded as combining diacritics. Those are
// ordinary cells to ratatui, so the diff, the alternate screen and redraws
// all keep the image where the buffer says it is.
// ---------------------------------------------------------------------------

/// Image id of the mark. Kept ≤ 255 so the placeholder foreground is an
/// indexed colour, which every palette-adaptation stage leaves untouched
/// (only RGB foregrounds are theme-remapped or contrast-lifted).
pub const KITTY_MARK_IMAGE_ID: u8 = 31;
/// The raster block both graphics tiers share: a cell is about 1:2, so 6×3
/// is square like the founder app-icon PNG. Kitty fills it with placeholder
/// cells; sixel sizes its pixels to it.
pub const MARK_IMAGE_COLS: u16 = 6;
pub const MARK_IMAGE_ROWS: u16 = 3;
/// Cell heights from here up get the 96 px raster; smaller cells get 48 px.
const KITTY_LARGE_CELL_PX: u16 = 24;

const MARK_PNG_96: &[u8] = include_bytes!("../../assets/mark-96.png");
const MARK_PNG_48: &[u8] = include_bytes!("../../assets/mark-48.png");

/// The placeholder character itself.
const PLACEHOLDER: char = '\u{10EEEE}';
/// Row/column diacritics, in protocol order: index `i` encodes `i`.
const PLACEHOLDER_DIACRITICS: [char; 16] = [
    '\u{0305}', '\u{030D}', '\u{030E}', '\u{0310}', '\u{0312}', '\u{033D}', '\u{033E}', '\u{033F}',
    '\u{0346}', '\u{034A}', '\u{034B}', '\u{034C}', '\u{0350}', '\u{0351}', '\u{0352}', '\u{0357}',
];

/// Capability query: a 1×1 RGB image sent with `a=q` is validated but never
/// stored; a supporting terminal answers `ESC _ G i=31;OK ESC \`.
const KITTY_QUERY: &[u8] = b"\x1b_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\x1b\\";
/// A terminal that supports the protocol answers within a millisecond.
const KITTY_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
/// Base64 payload per chunk (the protocol's maximum is 4096).
const KITTY_CHUNK: usize = 4096;

static KITTY_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. The query is only issued where the terminal is
/// one that could answer, so terminals that will never reply do not pay the
/// timeout at startup. tmux is excluded: image data needs a passthrough
/// wrapper there, which this tier does not do.
fn kitty_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("kitty")
        || term.contains("ghostty")
        || matches!(
            program.as_str(),
            "kitty" | "wezterm" | "ghostty" | "konsole"
        )
        || env("KITTY_WINDOW_ID").is_some()
        || env("KONSOLE_VERSION").is_some()
}

/// The terminal's answer to the capability query, decided: `OK` means it
/// validated our image; anything else (an error, no reply) does not.
fn kitty_query_accepted(reply: Option<&[u8]>) -> bool {
    reply.is_some_and(|reply| {
        let text = String::from_utf8_lossy(reply);
        text.contains("_G") && text.contains(";OK")
    })
}

/// Ask the terminal once whether it draws kitty graphics, and cache the
/// answer for the process. Call from the TUI entry point in the same window
/// as `palette::probe_terminal_background` — raw mode on, event loop not yet
/// reading stdin — since the reply comes back on stdin.
pub fn probe_kitty_graphics() -> bool {
    *KITTY_GRAPHICS.get_or_init(|| {
        kitty_candidate_env(|key| std::env::var(key).ok())
            && kitty_query_accepted(
                crate::palette::osc11::query_terminal(KITTY_QUERY, KITTY_QUERY_TIMEOUT).as_deref(),
            )
    })
}

/// Whether the probe said yes. `false` before the probe runs, so a render
/// that outruns startup paints the braille tier rather than empty cells.
#[must_use]
pub fn kitty_graphics_supported() -> bool {
    KITTY_GRAPHICS.get().copied().unwrap_or(false)
}

/// The byte stream that transmits `png` as image `id` and gives it a virtual
/// placement `cols`×`rows` cells. `q=2` silences the terminal's replies so
/// nothing lands in the input stream.
#[must_use]
pub fn kitty_transmit_sequence(png: &[u8], id: u8, cols: u16, rows: u16) -> Vec<u8> {
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    let encoded = STANDARD.encode(png);
    let chunks: Vec<&[u8]> = encoded.as_bytes().chunks(KITTY_CHUNK).collect();
    let mut out = Vec::with_capacity(encoded.len() + 64 * chunks.len());
    for (index, chunk) in chunks.iter().enumerate() {
        let more = u8::from(index + 1 < chunks.len());
        if index == 0 {
            out.extend_from_slice(format!("\x1b_Ga=T,f=100,q=2,i={id},m={more};").as_bytes());
        } else {
            out.extend_from_slice(format!("\x1b_Gm={more};").as_bytes());
        }
        out.extend_from_slice(chunk);
        out.extend_from_slice(b"\x1b\\");
    }
    out.extend_from_slice(format!("\x1b_Ga=p,U=1,q=2,i={id},c={cols},r={rows}\x1b\\").as_bytes());
    out
}

/// The byte stream that deletes image `id` and frees its data (`d=I`).
#[must_use]
pub fn kitty_delete_sequence(id: u8) -> Vec<u8> {
    format!("\x1b_Ga=d,d=I,q=2,i={id}\x1b\\").into_bytes()
}

/// Pick the raster for the terminal's cell height (`None` → the large one).
fn kitty_mark_png(cell_height_px: Option<u16>) -> &'static [u8] {
    match cell_height_px {
        Some(px) if px < KITTY_LARGE_CELL_PX => MARK_PNG_48,
        _ => MARK_PNG_96,
    }
}

/// Transmit the mark once, if the probe said the terminal draws it. Cheap
/// no-op otherwise. Write errors are logged, never fatal: a mark that fails
/// to upload simply leaves the placeholder cells blank until the next paint
/// falls back to braille.
pub fn transmit_kitty_mark<W: Write>(writer: &mut W, cell_height_px: Option<u16>) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_transmit_sequence(
        kitty_mark_png(cell_height_px),
        KITTY_MARK_IMAGE_ID,
        MARK_IMAGE_COLS,
        MARK_IMAGE_ROWS,
    );
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark transmission failed");
    }
}

/// Delete the transmitted mark on the way out so the terminal frees it.
pub fn delete_kitty_mark<W: Write>(writer: &mut W) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_delete_sequence(KITTY_MARK_IMAGE_ID);
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark deletion failed");
    }
}

/// One placeholder cell's symbol: the placeholder plus its row and column
/// diacritics.
#[must_use]
pub fn kitty_placeholder_symbol(row: u16, col: u16) -> String {
    let row = PLACEHOLDER_DIACRITICS[usize::from(row) % PLACEHOLDER_DIACRITICS.len()];
    let col = PLACEHOLDER_DIACRITICS[usize::from(col) % PLACEHOLDER_DIACRITICS.len()];
    format!("{PLACEHOLDER}{row}{col}")
}

/// Paint the `MARK_IMAGE_COLS`×`MARK_IMAGE_ROWS` placeholder block with its
/// top-left corner at `area`'s origin. Same surfacing as [`render_mark`], at
/// cell granularity: rows appear from the bottom as `progress` rises. Returns
/// the block's rect, or a zero-width rect when it does not fit.
pub fn render_kitty_placeholders(area: Rect, buf: &mut Buffer, progress: f32) -> Rect {
    if area.width < MARK_IMAGE_COLS || area.height < MARK_IMAGE_ROWS {
        return Rect::new(area.x, area.y, 0, 0);
    }
    let first_visible =
        u32::from(MARK_IMAGE_ROWS) - revealed_dot_rows(progress, u32::from(MARK_IMAGE_ROWS));
    for row in 0..MARK_IMAGE_ROWS {
        if u32::from(row) < first_visible {
            continue;
        }
        for col in 0..MARK_IMAGE_COLS {
            if let Some(cell) = buf.cell_mut((area.x + col, area.y + row)) {
                cell.set_symbol(&kitty_placeholder_symbol(row, col));
                cell.set_style(Style::default().fg(Color::Indexed(KITTY_MARK_IMAGE_ID)));
            }
        }
    }
    Rect::new(area.x, area.y, MARK_IMAGE_COLS, MARK_IMAGE_ROWS)
}

// ---------------------------------------------------------------------------
// Sixel graphics tier.
//
// For terminals that draw sixel (foot, mlterm, contour, sixel-enabled xterm,
// WezTerm with kitty graphics off) but never answered the kitty query.
// Sixel has no cell-owned image like kitty placeholders: pixels are drawn at
// the cursor when the DCS sequence is processed, so the launch header keeps
// the block blank with [`render_sixel_reserve`] and the event loop emits the
// positioned bytes from [`sixel_positioned_sequence`] after the frame draws,
// re-emitting only when the block moves and clearing it when the tier exits.
// A terminal that draws neither protocol keeps the braille tier.
// ---------------------------------------------------------------------------

/// Primary device-attributes request. A sixel terminal answers with its
/// capability parameters, e.g. `ESC [ ? 62 ; 4 c` (foot) or
/// `ESC [ ? 63 ; 1 ; 2 ; 4 ; 6 ; 7 ; 15 ; 18 c` (xterm-sixel); parameter 4 is
/// sixel graphics. Read with `query_terminal_csi`: a DA reply ends at its
/// `c` final byte, not at BEL/ST, so the shared OSC-11 reader would swallow
/// following input waiting for a terminator that never comes.
const SIXEL_QUERY: &[u8] = b"\x1b[c";
/// Same budget as the kitty query: answering terminals reply at once.
const SIXEL_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
/// Largest raster the encoder accepts, in pixels per edge. A 6×3-cell block
/// never approaches this; the bound keeps a corrupt size probe from
/// allocating a runaway palette.
const SIXEL_MAX_EDGE_PX: u32 = 1000;
/// Sixel registers the encoder may address (0..=255).
const SIXEL_MAX_REGISTERS: usize = 256;

static SIXEL_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. Same contract as the kitty gate: only
/// terminals that answer a DA query promptly, never tmux (image data needs
/// a passthrough wrapper there, which this tier does not do). The DA reply
/// itself decides — `xterm-256color` is listed because Terminal.app, iTerm2
/// and xterm.js answer it at once without parameter 4, which is a fast no.
fn sixel_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("foot")
        || term.contains("mlterm")
        || term.contains("contour")
        || term == "xterm"
        || term.starts_with("xterm-")
        || term == "st"
        || term.starts_with("st-")
        || program.as_str() == "wezterm"
}

/// The terminal's answer to the primary-DA query, decided: parameter `4`
/// (sixel graphics) present means it draws sixel; anything else does not.
fn da_reports_sixel(reply: Option<&[u8]>) -> bool {
    let Some(reply) = reply else {
        return false;
    };
    let text = String::from_utf8_lossy(reply);
    text.split('\x1b').any(|chunk| {
        let body = chunk.strip_prefix("[?").or_else(|| chunk.strip_prefix("["));
        body.is_some_and(|body| {
            body.strip_suffix('c')
                .is_some_and(|params| params.split(';').any(|param| param == "4"))
        })
    })
}

/// Ask the terminal once whether it draws sixel, and cache the answer for
/// the process. Call after [`probe_kitty_graphics`] in the same pre-loop
/// window (raw mode on, event loop not yet reading stdin): kitty answers
/// its own query, so reaching here means the terminal speaks another
/// protocol, and the launch header prefers kitty wherever both answer.
pub fn probe_sixel_graphics() -> bool {
    *SIXEL_GRAPHICS.get_or_init(|| {
        !kitty_graphics_supported()
            && sixel_candidate_env(|key| std::env::var(key).ok())
            && da_reports_sixel(
                crate::palette::osc11::query_terminal_csi(SIXEL_QUERY, SIXEL_QUERY_TIMEOUT)
                    .as_deref(),
            )
    })
}

/// Whether the probe said yes. `false` before the probe runs, so a render
/// that outruns startup paints the braille tier rather than an empty block.
#[must_use]
pub fn sixel_graphics_supported() -> bool {
    #[cfg(test)]
    if SIXEL_TEST_SUPPORT.load(std::sync::atomic::Ordering::SeqCst) {
        return true;
    }
    SIXEL_GRAPHICS.get().copied().unwrap_or(false)
}

#[cfg(test)]
static SIXEL_TEST_SUPPORT: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

/// Test-only support override so the frame reconciler's emit path is
/// exercisable without a live sixel terminal. Reset to `false` at the end
/// of the borrowing test. A leaked `true` is still harmless: tier selection
/// additionally requires a measured cell size, which only the borrowing
/// test sets.
#[cfg(test)]
pub fn set_sixel_supported_for_tests(supported: bool) {
    SIXEL_TEST_SUPPORT.store(supported, std::sync::atomic::Ordering::SeqCst);
}

/// The launch field behind the mark as sixel registers need it: the frame
/// paints the whole stage with this background first, so the raster's
/// transparent corners composite onto exactly this colour, and clearing the
/// block repaints exactly these cells. An RGB theme field is used directly;
/// a transparent (`Reset`) stage shows the terminal's own ground, so the
/// probed terminal background fills in — but only when the probe named an
/// RGB colour. Anything else (`Indexed` themes, unprobed terminals) is
/// `None`: the tier cannot composite exactly and declines, and the header
/// keeps the braille tier.
#[must_use]
pub fn sixel_field_bg(
    theme: &crate::palette::UiTheme,
    terminal_bg: Option<Color>,
) -> Option<(u8, u8, u8)> {
    match theme.surface_bg {
        Color::Rgb(r, g, b) => Some((r, g, b)),
        Color::Reset => match terminal_bg {
            Some(Color::Rgb(r, g, b)) => Some((r, g, b)),
            _ => None,
        },
        // Named and indexed theme surfaces cannot be composited exactly.
        _ => None,
    }
}

/// Pixel size of the sixel raster for a `cols`×`rows` cell block, or `None`
/// when the cell size is unknown or the raster would be absurd. Callers
/// treat `None` as "cannot size the raster" and keep the braille tier.
#[must_use]
pub fn sixel_pixel_size(cols: u16, rows: u16, cell_px: (u16, u16)) -> Option<(u32, u32)> {
    let width = u32::from(cols).checked_mul(u32::from(cell_px.0))?;
    let height = u32::from(rows).checked_mul(u32::from(cell_px.1))?;
    if width == 0 || height == 0 || width > SIXEL_MAX_EDGE_PX || height > SIXEL_MAX_EDGE_PX {
        return None;
    }
    Some((width, height))
}

/// Encode `pixels` (row-major `width`×`height` RGB over the field) as one
/// sixel DCS sequence, or `None` for an empty, absurd, or ragged raster.
/// Registers go to the most frequent colours first (the founder mark needs
/// a handful — its flat navy and white dominate), and rarer colours merge
/// into their nearest kept neighbour, so any input still encodes. Runs of
/// 4+ identical columns use the repeat introducer.
#[must_use]
pub fn sixel_encode(width: u32, height: u32, pixels: &[(u8, u8, u8)]) -> Option<Vec<u8>> {
    if width == 0
        || height == 0
        || width > SIXEL_MAX_EDGE_PX
        || height > SIXEL_MAX_EDGE_PX
        || pixels.len() != (width as usize) * (height as usize)
    {
        return None;
    }
    let width_usize = width as usize;
    let mut frequency: std::collections::HashMap<(u8, u8, u8), usize> =
        std::collections::HashMap::new();
    for pixel in pixels {
        *frequency.entry(*pixel).or_default() += 1;
    }
    let mut by_frequency: Vec<((u8, u8, u8), usize)> = frequency.into_iter().collect();
    by_frequency.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    by_frequency.truncate(SIXEL_MAX_REGISTERS);
    let palette: Vec<(u8, u8, u8)> = by_frequency.into_iter().map(|(colour, _)| colour).collect();
    let register = |pixel: &(u8, u8, u8)| -> usize {
        palette
            .iter()
            .position(|colour| colour == pixel)
            .unwrap_or_else(|| nearest_register(&palette, pixel))
    };
    let registers: Vec<usize> = pixels.iter().map(register).collect();

    let mut out = format!("\x1bPq\"1;1;{width};{height}").into_bytes();
    for (index, colour) in palette.iter().enumerate() {
        let (r, g, b) = (
            u32::from(colour.0) * 100 / 255,
            u32::from(colour.1) * 100 / 255,
            u32::from(colour.2) * 100 / 255,
        );
        out.extend_from_slice(format!("#{index};2;{r};{g};{b}").as_bytes());
    }
    let bands = height.div_ceil(6);
    for band in 0..bands {
        let mut used = vec![false; palette.len()];
        for x in 0..width_usize {
            for dy in 0..6 {
                let y = (band * 6 + dy) as usize;
                if y < height as usize {
                    used[registers[y * width_usize + x]] = true;
                }
            }
        }
        for (index, present) in used.iter().enumerate() {
            if !present {
                continue;
            }
            out.extend_from_slice(format!("#{index}").as_bytes());
            let mut run_char = 0u8;
            let mut run_len = 0usize;
            let flush = |out: &mut Vec<u8>, ch: u8, len: usize| {
                let mut remaining = len;
                while remaining >= 4 {
                    let take = remaining.min(255);
                    out.extend_from_slice(format!("!{take}{}", ch as char).as_bytes());
                    remaining -= take;
                }
                for _ in 0..remaining {
                    out.push(ch);
                }
            };
            for x in 0..width_usize {
                let mut bits = 0u8;
                for dy in 0..6 {
                    let y = (band * 6 + dy) as usize;
                    if y < height as usize && registers[y * width_usize + x] == index {
                        bits |= 1 << dy;
                    }
                }
                let ch = 0x3F + bits;
                if run_len > 0 && ch == run_char {
                    run_len += 1;
                } else {
                    if run_len > 0 {
                        flush(&mut out, run_char, run_len);
                    }
                    run_char = ch;
                    run_len = 1;
                }
            }
            if run_len > 0 {
                flush(&mut out, run_char, run_len);
            }
            out.push(b'$');
        }
        out.push(b'-');
    }
    out.extend_from_slice(b"\x1b\\");
    Some(out)
}

/// Nearest palette register to `pixel` by squared RGB distance. The palette
/// is never empty (a valid raster has at least one colour), so this always
/// resolves; ties go to the lowest register.
fn nearest_register(palette: &[(u8, u8, u8)], pixel: &(u8, u8, u8)) -> usize {
    let distance = |colour: &&(u8, u8, u8)| -> u32 {
        let dr = u32::from(colour.0.abs_diff(pixel.0));
        let dg = u32::from(colour.1.abs_diff(pixel.1));
        let db = u32::from(colour.2.abs_diff(pixel.2));
        dr * dr + dg * dg + db * db
    };
    palette
        .iter()
        .enumerate()
        .min_by_key(|(_, colour)| distance(colour))
        .map(|(index, _)| index)
        .unwrap_or(0)
}

/// Rasterise the founder app-icon PNG to the mark block's exact pixel size
/// and encode it for a sixel terminal. `field_bg` is the launch field the
/// transparent PNG corners composite onto ([`sixel_field_bg`]);
/// `cell_px` is the terminal's cell size in pixels. `None` when the raster
/// cannot be sized or decoded — the caller keeps the braille tier.
#[must_use]
pub fn sixel_mark_sequence(field_bg: (u8, u8, u8), cell_px: (u16, u16)) -> Option<Vec<u8>> {
    let (width, height) = sixel_pixel_size(MARK_IMAGE_COLS, MARK_IMAGE_ROWS, cell_px)?;
    let image = image::load_from_memory(MARK_PNG_96).ok()?;
    let resized = image.resize_exact(width, height, image::imageops::FilterType::Triangle);
    let rgba = resized.to_rgba8();
    let pixels: Vec<(u8, u8, u8)> = rgba
        .pixels()
        .map(|pixel| {
            let [r, g, b, a] = pixel.0;
            let alpha = u32::from(a);
            let blend = |fg: u8, bg: u8| {
                ((u32::from(fg) * alpha + u32::from(bg) * (255 - alpha) + 127) / 255) as u8
            };
            (
                blend(r, field_bg.0),
                blend(g, field_bg.1),
                blend(b, field_bg.2),
            )
        })
        .collect();
    sixel_encode(width, height, &pixels)
}

/// Position a sixel image over the mark block: save the cursor, jump to the
/// block's top-left, draw, restore. The image must already be sized to the
/// block ([`sixel_mark_sequence`]); `origin` is stage coordinates, which
/// are screen cells in fullscreen (CUP inside is 1-based).
#[must_use]
pub fn sixel_positioned_sequence(origin: Rect, sixel: &[u8]) -> Vec<u8> {
    let mut out = format!("\x1b7\x1b[{};{}H", origin.y + 1, origin.x + 1).into_bytes();
    out.extend_from_slice(sixel);
    out.extend_from_slice(b"\x1b8");
    out
}

/// Erase a stale sixel image by repainting its block with the field
/// background: writing text cells is what clears sixel graphics on every
/// supporting terminal. Cursor is saved and restored around the wipe.
#[must_use]
pub fn sixel_clear_sequence(block: Rect, field_bg: (u8, u8, u8)) -> Vec<u8> {
    let mut out = b"\x1b7".to_vec();
    let (r, g, b) = field_bg;
    for row in 0..block.height {
        out.extend_from_slice(
            format!(
                "\x1b[{};{}H\x1b[48;2;{r};{g};{b}m",
                block.y + row + 1,
                block.x + 1
            )
            .as_bytes(),
        );
        out.extend_from_slice(&vec![b' '; block.width as usize]);
        out.extend_from_slice(b"\x1b[0m");
    }
    out.extend_from_slice(b"\x1b8");
    out
}

/// Paint the sixel tier's reservation: the `MARK_IMAGE_COLS`×
/// `MARK_IMAGE_ROWS` block as blank cells with its top-left corner at
/// `area`'s origin. Deliberately static — spaces, no surfacing — so ratatui
/// never rewrites these cells after the first paint and the post-draw sixel
/// emission survives redraws. Returns the block's rect (stage coordinates),
/// or a zero-width rect when it does not fit.
pub fn render_sixel_reserve(area: Rect, buf: &mut Buffer) -> Rect {
    if area.width < MARK_IMAGE_COLS || area.height < MARK_IMAGE_ROWS {
        return Rect::new(area.x, area.y, 0, 0);
    }
    for row in 0..MARK_IMAGE_ROWS {
        for col in 0..MARK_IMAGE_COLS {
            if let Some(cell) = buf.cell_mut((area.x + col, area.y + row)) {
                cell.set_symbol(" ");
            }
        }
    }
    Rect::new(area.x, area.y, MARK_IMAGE_COLS, MARK_IMAGE_ROWS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_rung_matches_its_declared_footprint_in_braille_only() {
        for size in [MarkSize::Small, MarkSize::Tiny] {
            let (cols, rows) = size.cells();
            let art = size.rows();
            assert_eq!(art.len(), usize::from(rows), "{size:?} row count");
            for line in art {
                assert_eq!(
                    line.chars().count(),
                    usize::from(cols),
                    "{size:?} row {line:?} is not {cols} cells"
                );
                for glyph in line.chars() {
                    assert!(
                        glyph == ' ' || braille_bits(glyph).is_some(),
                        "{size:?} row {line:?} holds a non-braille glyph {glyph:?}"
                    );
                }
            }
            // Generated rows are trimmed: the first and last columns carry ink.
            assert!(art.iter().any(|line| line.starts_with(|c| c != ' ')));
            assert!(art.iter().any(|line| line.ends_with(|c| c != ' ')));
        }
    }

    #[test]
    fn the_mark_has_an_eye() {
        // The script carves the founder whale's eye as one cleared dot
        // inside the body (bit 0x08 of the eye cell). Without the carve the
        // small rung reads `⣟` there and the tiny rung `⠏`.
        assert_eq!(
            SMALL_ROWS[2].chars().nth(3),
            Some('⣗'),
            "small rung lost its carved eye"
        );
        assert_eq!(
            TINY_ROWS[1].chars().nth(3),
            Some('⠍'),
            "tiny rung lost its carved eye"
        );
    }

    #[test]
    fn surface_progress_is_a_monotonic_rise_that_settles_at_one() {
        assert!((surface_progress(0, 640) - 0.0).abs() < 1e-6);
        assert!((surface_progress(320, 640) - 0.5).abs() < 1e-3);
        assert!((surface_progress(640, 640) - 1.0).abs() < 1e-6);
        assert!((surface_progress(5_000, 640) - 1.0).abs() < 1e-6);
        let mut previous = -1.0;
        for ms in (0..=640).step_by(20) {
            let value = surface_progress(ms, 640);
            assert!(value >= previous, "regressed at {ms}ms");
            previous = value;
        }
    }

    #[test]
    fn a_zero_length_rise_is_settled_not_divided_by_zero() {
        assert!((surface_progress(0, 0) - 1.0).abs() < 1e-6);
    }

    #[test]
    fn the_mark_emerges_from_the_field_rather_than_fading_over_it() {
        let field = Color::Rgb(3, 7, 13);
        let gold = Color::Rgb(246, 196, 83);
        assert_eq!(lerp_color(field, gold, 0.0), field);
        assert_eq!(lerp_color(field, gold, 1.0), gold);
        let mid = lerp_color(field, gold, 0.5);
        assert_eq!(mid, Color::Rgb(125, 102, 48));
    }

    fn tilde_buffer(width: u16, height: u16) -> Buffer {
        let mut buf = Buffer::empty(Rect::new(0, 0, width, height));
        for x in 0..width {
            for y in 0..height {
                if let Some(cell) = buf.cell_mut((x, y)) {
                    cell.set_symbol("~");
                }
            }
        }
        buf
    }

    #[test]
    fn render_anchors_top_left_and_leaves_blanks_untouched() {
        let area = Rect::new(2, 1, 12, 5);
        let mut buf = tilde_buffer(14, 6);
        let painted = render_mark(
            area,
            &mut buf,
            MarkSize::Small,
            Color::Rgb(246, 196, 83),
            Color::Rgb(3, 7, 13),
            1.0,
        );
        assert_eq!(painted, Rect::new(2, 1, 7, 3));
        // Row 0 is `⢠⡶⠛⠧⠄  `: ink at the origin, trailing blanks keep the field.
        assert_eq!(buf.cell((1, 1)).map(|c| c.symbol()), Some("~"));
        assert_eq!(buf.cell((2, 1)).map(|c| c.symbol()), Some("⢠"));
        assert_eq!(buf.cell((7, 1)).map(|c| c.symbol()), Some("~"));
        assert_eq!(buf.cell((8, 1)).map(|c| c.symbol()), Some("~"));
        // Row 1 is full width: its last cell is ink.
        assert_eq!(buf.cell((8, 2)).map(|c| c.symbol()), Some("⠆"));
        assert_eq!(buf.cell((9, 2)).map(|c| c.symbol()), Some("~"));
    }

    #[test]
    fn the_mark_surfaces_from_the_bottom_dot_row_by_dot_row() {
        let ink = Color::Rgb(246, 196, 83);
        let field = Color::Rgb(3, 7, 13);
        let area = Rect::new(0, 0, 7, 3);
        // Nothing has surfaced at 0.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 0.0);
        assert!((0..7).all(|x| (0..3).all(|y| buf[(x, y)].symbol() == "~")));
        // Half way: the bottom six dot rows only — the top cell row is still
        // under water, and the middle row shows only its lower half.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 0.5);
        assert!(
            (0..7).all(|x| buf[(x, 0)].symbol() == "~"),
            "top row submerged"
        );
        let middle: u32 = (0..7)
            .filter_map(|x| buf[(x, 1)].symbol().chars().next())
            .filter_map(braille_bits)
            .fold(0, |acc, bits| acc | bits);
        assert_ne!(middle, 0, "middle row is partly up");
        assert_eq!(
            middle & (DOT_ROW_BITS[0] | DOT_ROW_BITS[1]),
            0,
            "the middle row's upper dots are still submerged"
        );
        // Settled: identical to a direct 1.0 paint, and fully the ink colour.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 1.0);
        for (y, line) in SMALL_ROWS.iter().enumerate() {
            for (x, glyph) in line.chars().enumerate() {
                let cell = &buf[(x as u16, y as u16)];
                if glyph == ' ' {
                    assert_eq!(cell.symbol(), "~");
                } else {
                    assert_eq!(cell.symbol(), glyph.to_string());
                    assert_eq!(cell.fg, ink);
                }
            }
        }
    }

    #[test]
    fn render_declines_rather_than_clipping_when_the_area_is_too_small() {
        let area = Rect::new(0, 0, 6, 3);
        let mut buf = Buffer::empty(area);
        let painted = render_mark(
            area,
            &mut buf,
            MarkSize::Small,
            Color::Rgb(246, 196, 83),
            Color::Rgb(3, 7, 13),
            1.0,
        );
        assert_eq!(painted.width, 0);
        assert_eq!(buf.cell((0, 0)).map(|c| c.symbol()), Some(" "));
    }

    #[test]
    fn kitty_candidates_are_the_terminals_that_can_answer_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-kitty")])));
        assert!(kitty_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-ghostty")])));
        assert!(kitty_candidate_env(env(&[("KONSOLE_VERSION", "230800")])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-256color"),
            ("TERM_PROGRAM", "Apple_Terminal")
        ])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-kitty"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_query_is_accepted_only_on_an_ok_reply() {
        assert!(kitty_query_accepted(Some(b"\x1b_Gi=31;OK")));
        assert!(!kitty_query_accepted(Some(b"\x1b_Gi=31;EINVAL:bad")));
        assert!(!kitty_query_accepted(Some(b"\x1b[?1;2c")));
        assert!(!kitty_query_accepted(None));
    }

    #[test]
    fn the_transmit_stream_is_chunked_png_then_a_virtual_placement() {
        let bytes = kitty_transmit_sequence(MARK_PNG_96, 31, 6, 3);
        let text = String::from_utf8(bytes).expect("ASCII stream");
        let commands: Vec<&str> = text.split("\x1b\\").filter(|s| !s.is_empty()).collect();
        assert!(commands.len() >= 3, "{} commands", commands.len());
        assert!(commands[0].starts_with("\x1b_Ga=T,f=100,q=2,i=31,m=1;"));
        for chunk in &commands[..commands.len() - 1] {
            let payload = chunk.split_once(';').map(|(_, p)| p).unwrap_or("");
            assert!(
                payload.len() <= KITTY_CHUNK,
                "chunk over 4096: {}",
                payload.len()
            );
            assert!(
                payload
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'='),
                "chunk is not base64"
            );
        }
        let last_chunk = commands[commands.len() - 2];
        assert!(
            last_chunk.starts_with("\x1b_Gm=0;"),
            "final chunk ends the upload"
        );
        assert_eq!(
            commands[commands.len() - 1],
            "\x1b_Ga=p,U=1,q=2,i=31,c=6,r=3"
        );
        // The PNG really is one: decode the payload back.
        use base64::{Engine as _, engine::general_purpose::STANDARD};
        let payload: String = commands[..commands.len() - 1]
            .iter()
            .map(|chunk| chunk.split_once(';').map(|(_, p)| p).unwrap_or(""))
            .collect();
        let decoded = STANDARD.decode(payload).expect("base64 round-trips");
        assert_eq!(decoded, MARK_PNG_96);
        assert!(decoded.starts_with(b"\x89PNG"));
        assert_eq!(kitty_delete_sequence(31), b"\x1b_Ga=d,d=I,q=2,i=31\x1b\\");
    }

    #[test]
    fn the_bundled_rasters_decode_to_their_declared_sizes() {
        for (png, edge) in [(MARK_PNG_96, 96u32), (MARK_PNG_48, 48u32)] {
            let image = image::load_from_memory(png).expect("bundled mark decodes");
            assert_eq!((image.width(), image.height()), (edge, edge));
        }
        assert_eq!(kitty_mark_png(None), MARK_PNG_96);
        assert_eq!(kitty_mark_png(Some(16)), MARK_PNG_48);
        assert_eq!(kitty_mark_png(Some(32)), MARK_PNG_96);
    }

    #[test]
    fn placeholders_carry_the_image_id_and_their_own_coordinates() {
        let area = Rect::new(1, 0, 8, 4);
        let mut buf = tilde_buffer(9, 4);
        let painted = render_kitty_placeholders(area, &mut buf, 1.0);
        assert_eq!(painted, Rect::new(1, 0, 6, 3));
        let cell = &buf[(1u16, 0u16)];
        assert_eq!(cell.symbol(), "\u{10EEEE}\u{0305}\u{0305}");
        assert_eq!(cell.fg, Color::Indexed(KITTY_MARK_IMAGE_ID));
        assert_eq!(buf[(6u16, 2u16)].symbol(), "\u{10EEEE}\u{030E}\u{033D}");
        assert_eq!(buf[(7u16, 0u16)].symbol(), "~", "outside the block");
        assert_eq!(buf[(1u16, 3u16)].symbol(), "~", "below the block");
        // Surfacing at cell granularity: under a third of the way up, only
        // the bottom row is placed.
        let mut buf = tilde_buffer(9, 4);
        render_kitty_placeholders(area, &mut buf, 0.3);
        assert_eq!(buf[(1u16, 0u16)].symbol(), "~");
        assert_eq!(buf[(1u16, 1u16)].symbol(), "~");
        assert!(buf[(1u16, 2u16)].symbol().starts_with('\u{10EEEE}'));
    }
    #[test]
    fn sixel_candidates_are_the_terminals_that_answer_da_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(sixel_candidate_env(env(&[("TERM", "foot")])));
        assert!(sixel_candidate_env(env(&[("TERM", "foot-extra")])));
        assert!(sixel_candidate_env(env(&[("TERM", "mlterm")])));
        assert!(sixel_candidate_env(env(&[("TERM", "contour")])));
        // `xterm-256color` is a candidate even though most of its owners
        // decline: Terminal.app, iTerm2 and xterm.js answer DA at once
        // without parameter 4, which is a fast no rather than a timeout.
        assert!(sixel_candidate_env(env(&[("TERM", "xterm-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM", "st-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(!sixel_candidate_env(env(&[])));
        assert!(!sixel_candidate_env(env(&[("TERM", "dumb")])));
        assert!(!sixel_candidate_env(env(&[
            ("TERM", "foot"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_da_reply_decides_on_parameter_four_only() {
        // foot: sixel present.
        assert!(da_reports_sixel(Some(b"\x1b[?62;4c")));
        // xterm-sixel: sixel among other capabilities.
        assert!(da_reports_sixel(Some(b"\x1b[?63;1;2;4;6;7;15;18c")));
        // Plain xterm: answers, no sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;1;2;6;7c")));
        // A 4 inside another parameter is not sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;44c")));
        // A kitty reply is not a DA reply.
        assert!(!da_reports_sixel(Some(b"\x1b_Gi=31;OK\x1b\\")));
        assert!(!da_reports_sixel(None));
    }

    #[test]
    fn sixel_pixel_size_multiplies_cells_and_rejects_nonsense() {
        assert_eq!(sixel_pixel_size(6, 3, (10, 20)), Some((60, 60)));
        assert_eq!(sixel_pixel_size(6, 3, (0, 20)), None);
        assert_eq!(sixel_pixel_size(6, 3, (200, 200)), None);
        assert_eq!(
            sixel_pixel_size(u16::MAX, u16::MAX, (u16::MAX, u16::MAX)),
            None
        );
    }

    #[test]
    fn sixel_encode_paints_a_solid_block_with_one_repeat_per_colour() {
        // 6x6 solid red: one register, one band, a single `!6` run.
        // Red 200 scales to 78, 10 scales to 3 (integer division).
        let red = (200u8, 10u8, 10u8);
        let pixels = vec![red; 36];
        let bytes = sixel_encode(6, 6, &pixels).expect("solid block encodes");
        assert_eq!(
            String::from_utf8(bytes).expect("ASCII stream"),
            "\x1bPq\"1;1;6;6#0;2;78;3;3#0!6~$-\x1b\\"
        );
    }

    #[test]
    fn sixel_encode_composes_columns_without_repeats_literally() {
        // 2x6: a blue column beside a red one. No run reaches 4, so every
        // column is literal.
        let blue = (0u8, 0u8, 255u8);
        let red = (255u8, 0u8, 0u8);
        let pixels = vec![
            blue, red, blue, red, blue, red, blue, red, blue, red, blue, red,
        ];
        let bytes = sixel_encode(2, 6, &pixels).expect("two columns encode");
        assert_eq!(
            String::from_utf8(bytes).expect("ASCII stream"),
            "\x1bPq\"1;1;2;6#0;2;0;0;100#1;2;100;0;0#0~?$#1?~$-\x1b\\"
        );
    }

    #[test]
    fn sixel_encode_rejects_empty_absurd_and_ragged_rasters() {
        assert_eq!(sixel_encode(0, 6, &[]), None);
        assert_eq!(sixel_encode(6, 0, &[]), None);
        assert_eq!(sixel_encode(1001, 6, &vec![(0u8, 0u8, 0u8); 6006]), None);
        assert_eq!(sixel_encode(2, 6, &[(0u8, 0u8, 0u8); 11]), None);
    }

    #[test]
    fn sixel_encode_merges_colours_past_256_registers() {
        // 300 distinct greys in 30x10 bands: only 256 registers exist, so
        // the tail merges into its nearest kept neighbour — and the
        // sequence still carries all 256 introducers.
        let pixels: Vec<(u8, u8, u8)> = (0..300u32)
            .map(|i| {
                let v = (i % 256) as u8;
                (v, v, v)
            })
            .collect();
        let bytes = sixel_encode(30, 10, &pixels).expect("over-full palette still encodes");
        let text = String::from_utf8(bytes).expect("ASCII stream");
        assert!(text.starts_with("\x1bPq\"1;1;30;10"));
        assert!(text.ends_with("-\x1b\\"));
        // Parse the palette definitions (`#N;2;R;G;B` tokens before the
        // first band): grey values like `2;2;2` contain ";2;" inside the
        // values, so a substring count would overcount.
        let mut rest = text
            .strip_prefix("\x1bPq\"1;1;30;10")
            .expect("header first");
        let mut definitions = 0;
        loop {
            let digits: String = rest
                .strip_prefix('#')
                .unwrap_or("")
                .chars()
                .take_while(|c| c.is_ascii_digit())
                .collect();
            let after = &rest[1 + digits.len()..];
            if let Some(values) = after.strip_prefix(";2;") {
                definitions += 1;
                rest = &values[values.find('#').expect("band follows")..];
            } else {
                break;
            }
        }
        assert_eq!(definitions, 256, "one definition per register");
    }

    #[test]
    fn the_positioned_stream_saves_jumps_draws_and_restores() {
        let sixel = sixel_encode(6, 6, &[(1u8, 2u8, 3u8); 36]).expect("encodes");
        let bytes = sixel_positioned_sequence(Rect::new(4, 2, 6, 3), &sixel);
        let text = String::from_utf8(bytes).expect("ASCII stream");
        assert!(text.starts_with("\x1b7\x1b[3;5H\x1bPq"), "{text:?}");
        assert!(text.ends_with("\x1b\\\x1b8"), "{text:?}");
    }

    #[test]
    fn the_clear_stream_repaints_the_block_with_the_field() {
        let bytes = sixel_clear_sequence(Rect::new(4, 2, 6, 3), (1, 2, 3));
        assert_eq!(
            String::from_utf8(bytes).expect("ASCII stream"),
            "\x1b7\x1b[3;5H\x1b[48;2;1;2;3m      \x1b[0m\
             \x1b[4;5H\x1b[48;2;1;2;3m      \x1b[0m\
             \x1b[5;5H\x1b[48;2;1;2;3m      \x1b[0m\x1b8"
        );
    }

    #[test]
    fn the_sixel_reserve_blanks_the_block_and_reports_it() {
        let area = Rect::new(2, 1, 12, 5);
        let mut buf = tilde_buffer(14, 6);
        let reserved = render_sixel_reserve(area, &mut buf);
        assert_eq!(reserved, Rect::new(2, 1, 6, 3));
        for y in 1..4 {
            for x in 2..8 {
                assert_eq!(buf.cell((x, y)).map(|c| c.symbol()), Some(" "));
            }
        }
        assert_eq!(buf.cell((8, 1)).map(|c| c.symbol()), Some("~"));
        // Too narrow: declines with a zero-width rect and touches nothing.
        let mut buf = tilde_buffer(6, 3);
        let declined = render_sixel_reserve(Rect::new(0, 0, 5, 3), &mut buf);
        assert_eq!(declined.width, 0);
        assert_eq!(buf.cell((0, 0)).map(|c| c.symbol()), Some("~"));
    }

    #[test]
    fn the_bundled_app_icon_decodes_square_with_transparent_corners() {
        // The raster-tier PNG is the founder app icon (white whale on the
        // navy rounded square), not a monochrome silhouette: its corners
        // are transparent and its body is navy with a white whale.
        let image = image::load_from_memory(MARK_PNG_96).expect("bundled mark decodes");
        let rgba = image.to_rgba8();
        assert_eq!((rgba.width(), rgba.height()), (96, 96));
        assert_eq!(rgba.get_pixel(0, 0)[3], 0, "corner is transparent");
        let mut navy = 0usize;
        let mut white = 0usize;
        for pixel in rgba.pixels() {
            let [r, g, b, a] = pixel.0;
            if a < 128 {
                continue;
            }
            if b > 60 && u16::from(b) > u16::from(r) + 25 {
                navy += 1;
            }
            if r > 200 && g > 200 && b > 200 {
                white += 1;
            }
        }
        assert!(navy > 1000, "navy field present ({navy})");
        assert!(white > 500, "white whale present ({white})");
    }

    #[test]
    fn sixel_field_bg_prefers_theme_rgb_then_probed_reset() {
        let mut theme = crate::palette::ThemeId::Underwater.ui_theme();
        theme.surface_bg = Color::Rgb(1, 2, 3);
        assert_eq!(sixel_field_bg(&theme, None), Some((1, 2, 3)));
        theme.surface_bg = Color::Reset;
        assert_eq!(
            sixel_field_bg(&theme, Some(Color::Rgb(4, 5, 6))),
            Some((4, 5, 6))
        );
        assert_eq!(sixel_field_bg(&theme, Some(Color::Indexed(7))), None);
        assert_eq!(sixel_field_bg(&theme, None), None);
        theme.surface_bg = Color::Indexed(8);
        assert_eq!(sixel_field_bg(&theme, Some(Color::Rgb(4, 5, 6))), None);
    }

    #[test]
    fn the_bundled_app_icon_encodes_to_a_bounded_sixel_sequence() {
        // End to end over the real founder derivative: 6x3 cells at
        // 10x20 px cells rasterise to 60x60 px and stay small enough to
        // re-emit on moves without a care.
        let bytes = sixel_mark_sequence((3, 7, 13), (10, 20)).expect("founder icon encodes");
        let text = String::from_utf8(bytes).expect("ASCII stream");
        assert!(text.starts_with("\x1bPq\"1;1;60;60"), "{text:.80}?");
        assert!(text.ends_with("-\x1b\\"));
        assert!(
            text.len() < 64 * 1024,
            "flat logo stays small ({} bytes)",
            text.len()
        );
    }
}
